{
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_calendar",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "yyyy-mm-dd"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Key",
            "dataType": "string",
            "sourceColumn": "Month Key"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "#,0"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          }
        ],
        "partitions": [
          {
            "name": "dim_calendar",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"RGF0ZSxNb250aCxNb250aCBLZXksWWVhcixRdWFydGVyCjIwMjMtMDEtMDEsSmFuIDIwMjMsMjAyMy0wMSwyMDIzLFExCjIwMjMtMDItMDEsRmViIDIwMjMsMjAyMy0wMiwyMDIzLFExCjIwMjMtMDMtMDEsTWFyIDIwMjMsMjAyMy0wMywyMDIzLFExCjIwMjMtMDQtMDEsQXByIDIwMjMsMjAyMy0wNCwyMDIzLFEyCjIwMjMtMDUtMDEsTWF5IDIwMjMsMjAyMy0wNSwyMDIzLFEyCjIwMjMtMDYtMDEsSnVuIDIwMjMsMjAyMy0wNiwyMDIzLFEyCjIwMjMtMDctMDEsSnVsIDIwMjMsMjAyMy0wNywyMDIzLFEzCjIwMjMtMDgtMDEsQXVnIDIwMjMsMjAyMy0wOCwyMDIzLFEzCjIwMjMtMDktMDEsU2VwIDIwMjMsMjAyMy0wOSwyMDIzLFEzCjIwMjMtMTAtMDEsT2N0IDIwMjMsMjAyMy0xMCwyMDIzLFE0CjIwMjMtMTEtMDEsTm92IDIwMjMsMjAyMy0xMSwyMDIzLFE0CjIwMjMtMTItMDEsRGVjIDIwMjMsMjAyMy0xMiwyMDIzLFE0CjIwMjQtMDEtMDEsSmFuIDIwMjQsMjAyNC0wMSwyMDI0LFExCjIwMjQtMDItMDEsRmViIDIwMjQsMjAyNC0wMiwyMDI0LFExCjIwMjQtMDMtMDEsTWFyIDIwMjQsMjAyNC0wMywyMDI0LFExCjIwMjQtMDQtMDEsQXByIDIwMjQsMjAyNC0wNCwyMDI0LFEyCjIwMjQtMDUtMDEsTWF5IDIwMjQsMjAyNC0wNSwyMDI0LFEyCjIwMjQtMDYtMDEsSnVuIDIwMjQsMjAyNC0wNiwyMDI0LFEyCjIwMjQtMDctMDEsSnVsIDIwMjQsMjAyNC0wNywyMDI0LFEzCjIwMjQtMDgtMDEsQXVnIDIwMjQsMjAyNC0wOCwyMDI0LFEzCjIwMjQtMDktMDEsU2VwIDIwMjQsMjAyNC0wOSwyMDI0LFEzCjIwMjQtMTAtMDEsT2N0IDIwMjQsMjAyNC0xMCwyMDI0LFE0CjIwMjQtMTEtMDEsTm92IDIwMjQsMjAyNC0xMSwyMDI0LFE0CjIwMjQtMTItMDEsRGVjIDIwMjQsMjAyNC0xMiwyMDI0LFE0CjIwMjUtMDEtMDEsSmFuIDIwMjUsMjAyNS0wMSwyMDI1LFExCjIwMjUtMDItMDEsRmViIDIwMjUsMjAyNS0wMiwyMDI1LFExCjIwMjUtMDMtMDEsTWFyIDIwMjUsMjAyNS0wMywyMDI1LFExCjIwMjUtMDQtMDEsQXByIDIwMjUsMjAyNS0wNCwyMDI1LFEyCjIwMjUtMDUtMDEsTWF5IDIwMjUsMjAyNS0wNSwyMDI1LFEyCjIwMjUtMDYtMDEsSnVuIDIwMjUsMjAyNS0wNiwyMDI1LFEyCjIwMjUtMDctMDEsSnVsIDIwMjUsMjAyNS0wNywyMDI1LFEzCjIwMjUtMDgtMDEsQXVnIDIwMjUsMjAyNS0wOCwyMDI1LFEzCjIwMjUtMDktMDEsU2VwIDIwMjUsMjAyNS0wOSwyMDI1LFEzCjIwMjUtMTAtMDEsT2N0IDIwMjUsMjAyNS0xMCwyMDI1LFE0CjIwMjUtMTEtMDEsTm92IDIwMjUsMjAyNS0xMSwyMDI1LFE0CjIwMjUtMTItMDEsRGVjIDIwMjUsMjAyNS0xMiwyMDI1LFE0CjIwMjYtMDEtMDEsSmFuIDIwMjYsMjAyNi0wMSwyMDI2LFExCjIwMjYtMDItMDEsRmViIDIwMjYsMjAyNi0wMiwyMDI2LFExCjIwMjYtMDMtMDEsTWFyIDIwMjYsMjAyNi0wMywyMDI2LFExCjIwMjYtMDQtMDEsQXByIDIwMjYsMjAyNi0wNCwyMDI2LFEyCjIwMjYtMDUtMDEsTWF5IDIwMjYsMjAyNi0wNSwyMDI2LFEyCjIwMjYtMDYtMDEsSnVuIDIwMjYsMjAyNi0wNiwyMDI2LFEyCjIwMjYtMDctMDEsSnVsIDIwMjYsMjAyNi0wNywyMDI2LFEzCjIwMjYtMDgtMDEsQXVnIDIwMjYsMjAyNi0wOCwyMDI2LFEzCjIwMjYtMDktMDEsU2VwIDIwMjYsMjAyNi0wOSwyMDI2LFEzCjIwMjYtMTAtMDEsT2N0IDIwMjYsMjAyNi0xMCwyMDI2LFE0CjIwMjYtMTEtMDEsTm92IDIwMjYsMjAyNi0xMSwyMDI2LFE0CjIwMjYtMTItMDEsRGVjIDIwMjYsMjAyNi0xMiwyMDI2LFE0CjIwMjctMDEtMDEsSmFuIDIwMjcsMjAyNy0wMSwyMDI3LFExCjIwMjctMDItMDEsRmViIDIwMjcsMjAyNy0wMiwyMDI3LFExCjIwMjctMDMtMDEsTWFyIDIwMjcsMjAyNy0wMywyMDI3LFExCjIwMjctMDQtMDEsQXByIDIwMjcsMjAyNy0wNCwyMDI3LFEyCjIwMjctMDUtMDEsTWF5IDIwMjcsMjAyNy0wNSwyMDI3LFEyCjIwMjctMDYtMDEsSnVuIDIwMjcsMjAyNy0wNiwyMDI3LFEyCg==\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Date\", type date}, {\"Month\", type text}, {\"Month Key\", type text}, {\"Year\", Int64.Type}, {\"Quarter\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "monthly_performance",
        "columns": [
          {
            "name": "Month",
            "dataType": "dateTime",
            "sourceColumn": "Month",
            "formatString": "mmm yyyy"
          },
          {
            "name": "Month Key",
            "dataType": "string",
            "sourceColumn": "Month Key"
          },
          {
            "name": "Period",
            "dataType": "string",
            "sourceColumn": "Period"
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "sourceColumn": "Revenue"
          },
          {
            "name": "Budget Revenue",
            "dataType": "double",
            "sourceColumn": "Budget Revenue"
          },
          {
            "name": "Gross Profit",
            "dataType": "double",
            "sourceColumn": "Gross Profit"
          },
          {
            "name": "Operating Expense",
            "dataType": "double",
            "sourceColumn": "Operating Expense"
          },
          {
            "name": "EBITDA",
            "dataType": "double",
            "sourceColumn": "EBITDA"
          },
          {
            "name": "Budget EBITDA",
            "dataType": "double",
            "sourceColumn": "Budget EBITDA"
          },
          {
            "name": "Depreciation",
            "dataType": "double",
            "sourceColumn": "Depreciation"
          },
          {
            "name": "EBIT",
            "dataType": "double",
            "sourceColumn": "EBIT"
          },
          {
            "name": "Net Income",
            "dataType": "double",
            "sourceColumn": "Net Income"
          },
          {
            "name": "Ending Cash",
            "dataType": "double",
            "sourceColumn": "Ending Cash"
          },
          {
            "name": "Headcount",
            "dataType": "int64",
            "sourceColumn": "Headcount",
            "formatString": "#,0"
          },
          {
            "name": "CCC Days",
            "dataType": "double",
            "sourceColumn": "CCC Days"
          },
          {
            "name": "Gross Margin Rate",
            "dataType": "double",
            "sourceColumn": "Gross Margin Rate"
          },
          {
            "name": "EBITDA Margin",
            "dataType": "double",
            "sourceColumn": "EBITDA Margin"
          },
          {
            "name": "EBITDA Attainment",
            "dataType": "double",
            "sourceColumn": "EBITDA Attainment"
          },
          {
            "name": "Forecast Accuracy",
            "dataType": "double",
            "sourceColumn": "Forecast Accuracy"
          }
        ],
        "partitions": [
          {
            "name": "monthly_performance",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"TW9udGgsTW9udGggS2V5LFBlcmlvZCxSZXZlbnVlLEJ1ZGdldCBSZXZlbnVlLEdyb3NzIFByb2ZpdCxPcGVyYXRpbmcgRXhwZW5zZSxFQklUREEsQnVkZ2V0IEVCSVREQSxEZXByZWNpYXRpb24sRUJJVCxOZXQgSW5jb21lLEVuZGluZyBDYXNoLEhlYWRjb3VudCxDQ0MgRGF5cyxHcm9zcyBNYXJnaW4gUmF0ZSxFQklUREEgTWFyZ2luLEVCSVREQSBBdHRhaW5tZW50LEZvcmVjYXN0IEFjY3VyYWN5CjIwMjMtMDEtMDEsMjAyMy0wMSxBY3R1YWwsODI5NjUyNDkuNjcsODI5NjUyNDkuNjcsNDEyMDE5ODguOSwzOTI2NzU2Ni44MSwxOTM0NDIyLjA4OTk5OTk5NiwxOTM0NDIyLjA4OTk5OTk5NiwwLjAsMTkzNDQyMi4wODk5OTk5OTYsMTEzNTgxNi41Njk5OTk5OTYsNTMxMzU4MTYuNTcsMTkyLDU2LjAsMC40OTY2MTc0Mjc5NDU4NDE4LDAuMDIzMzE2MDUyMTc0Nzg3NSwxLjAsMS4wCjIwMjMtMDItMDEsMjAyMy0wMixBY3R1YWwsODcyNjUxMzEuMzgsODcyNjUxMzEuMzgsNDM2MTU0MTcuNTIsMzk1NjQ3MzcuMjUsNDA1MDY4MC4yNjk5OTk5OTYsNDA1MDY4MC4yNjk5OTk5OTYsMC4wLDQwNTA2ODAuMjY5OTk5OTk2LDI3MjMwMTAuMTk5OTk5OTk2LDM1MTQ1OTMxLjk5LDE5Miw1NS43MywwLjQ5OTgwMzQ5MzQ0ODg4NTksMC4wNDY0MTgwODQ4MTc0MTgzLDEuMCwxLjAKMjAyMy0wMy0wMSwyMDIzLTAzLEFjdHVhbCw5NTUzMjEzMi41Miw5NTUzMjEzMi41Miw0NzcyOTE3NC4zNyw0MDE4NzU0OS41Nyw3NTQxNjI0Ljc5OTk5OTk5Nyw3NTQxNjI0Ljc5OTk5OTk5NywwLjAsNzU0MTYyNC43OTk5OTk5OTcsNTM0MTIxOC41OTk5OTk5OTcsMzg5NDk4MTYuNTMsMTkyLDU1LjQ2LDAuNDk5NjEzODI3NDIwOTIyNywwLjA3ODk0MzMzMTQzMjcxMDYsMS4wLDEuMAoyMDIzLTA0LTAxLDIwMjMtMDQsQWN0dWFsLDk5OTk2NTAzLjUzLDk5OTk2NTAzLjUzLDQ5NTExNzc4LjIzLDQxODc4NjIyLjk2LDc2MzMxNTUuMjcwMDAwMDAzLDc2MzMxNTUuMjcwMDAwMDAzLDAuMCw3NjMzMTU1LjI3MDAwMDAwMyw1NDA5ODY2LjQ1MDAwMDAwMywzMTc2MDE3OS4wLDE5MSw1NS4xOSwwLjQ5NTEzNTA5NDU1MDA0MDQsMC4wNzYzMzQyMjE3MDMxNjE2LDEuMCwxLjAKMjAyMy0wNS0wMSwyMDIzLTA1LEFjdHVhbCwxMDI4OTEwMzcuMzQsMTAyODkxMDM3LjM0LDUxNDI5NDIwLjgyMDAwMDAxLDQyMjU0MzI2LjMsOTE3NTA5NC41MjAwMDAwMSw5MTc1MDk0LjUyMDAwMDAxLDAuMCw5MTc1MDk0LjUyMDAwMDAxLDY1NjYzMjAuODkwMDAwMDExLDM3MTY4MTc5LjU5LDE5MCw1NC45MiwwLjQ5OTg0MzU0NDY4MTY3MzMsMC4wODkxNzI5MjI3MDczNjA5LDEuMCwxLjAKMjAyMy0wNi0wMSwyMDIzLTA2LEFjdHVhbCwxMDQ5ODkxNDMuMjcsMTA0OTg5MTQzLjI3LDUyNjA4ODE2LjA1LDQyMjM4MzQyLjAzLDEwMzcwNDc0LjAxOTk5OTk5NiwxMDM3MDQ3NC4wMTk5OTk5OTYsMTY5NzkxLjY3LDEwMjAwNjgyLjM0OTk5OTk5Niw3MzM1NTExLjc1OTk5OTk5NiwzMjY3Mjc1NC4wMSwxOTIsNTQuNjUsMC41MDEwODgxNTQ1NjAwMDI0LDAuMDk4Nzc2NjMyNDg3ODk3MywxLjAsMS4wCjIwMjMtMDctMDEsMjAyMy0wNyxBY3R1YWwsMTAzNTk0NjMyLjE0LDEwMzU5NDYzMi4xNCw1MjMxNjczOS45Miw0MjgzMzI5MC4yNyw5NDgzNDQ5LjY1MDAwMDAwNiw5NDgzNDQ5LjY1MDAwMDAwNiwxNjk3OTEuNjcsOTMxMzY1Ny45ODAwMDAwMDYsNjY3MDI0My40ODAwMDAwMDYsNDYyNTgyMjYuOTMsMTk4LDU0LjM4LDAuNTA1MDE0MDAzNTE4MDM5OCwwLjA5MTU0MzgzMjQ3NTY0MjgsMS4wLDEuMAoyMDIzLTA4LTAxLDIwMjMtMDgsQWN0dWFsLDk4NzI1NTE3LjM3LDk4NzI1NTE3LjM3LDQ5NTcwOTEzLjUxMDAwMDAwNSw0MzEwMzQzMC4wMyw2NDY3NDgzLjQ4MDAwMDAwNCw2NDY3NDgzLjQ4MDAwMDAwNCwxNjk3OTEuNjcsNjI5NzY5MS44MTAwMDAwMDQsNDQwODI2OC44NjAwMDAwMDQsNTcwMTEwMjcuNDEsMTk3LDU0LjExLDAuNTAyMTA4NDE5NjkyNzUxNywwLjA2NTUwOTc0NTEyMjU0NDEsMS4wLDEuMAoyMDIzLTA5LTAxLDIwMjMtMDksQWN0dWFsLDExMTIzOTc2NS4xMywxMTEyMzk3NjUuMTMsNTUyMjg5MjEuOTIsNDM0ODYyMDAuODgsMTE3NDI3MjEuMDM5OTk5OTkyLDExNzQyNzIxLjAzOTk5OTk5MiwxNjk3OTEuNjcsMTE1NzI5MjkuMzY5OTk5OTkyLDgzNjQ2OTcuMDI5OTk5OTkyLDM5ODA2MzU0LjAsMTk3LDUzLjg0LDAuNDk2NDg1NDIzNjc0MzIwOCwwLjEwNTU2MjI2MDI3ODc0OTIsMS4wLDEuMAoyMDIzLTEwLTAxLDIwMjMtMTAsQWN0dWFsLDExNTIyNDQzNS40MywxMTUyMjQ0MzUuNDMsNTc1MjA0NDYuMTMwMDAwMDEsNDQwNDMxMTcuNTMsMTM0NzczMjguNjAwMDAwMDA3LDEzNDc3MzI4LjYwMDAwMDAwNywyNzcyOTEuNjcwMDAwMDAwMDQsMTMyMDAwMzYuOTMwMDAwMDA3LDk1ODUwMjcuNzAwMDAwMDA5LDMwMDkzMTE3LjY1LDE5Nyw2MC43NywwLjQ5OTIwMzU0MDU5NzQ2NTEsMC4xMTY5NjU4ODk2NTQ0MzU1LDEuMCwxLjAKMjAyMy0xMS0wMSwyMDIzLTExLEFjdHVhbCwxMjIwMzU4NjcuODYsMTIyMDM1ODY3Ljg2LDYxNDUyOTYyLjk4LDQ0Nzk3ODYxLjY2LDE2NjU1MTAxLjMyLDE2NjU1MTAxLjMyLDI3NzI5MS42NzAwMDAwMDAwNCwxNjM3NzgwOS42NSwxMTk2ODM1Ny4yNCwyNjQ0NTkwOS45LDE5Niw2MC41LDAuNTAzNTY0NzYzODQ4NzY1LDAuMTM2NDc3MDk5ODIzNjkxMSwxLjAsMS4wCjIwMjMtMTItMDEsMjAyMy0xMixBY3R1YWwsMTMwODEwODAwLjYzLDEzMDgxMDgwMC42Myw2NjM5Mjg0Ni43NCw0NTc2Mjk2MS4xMiwyMDYyOTg4NS42MiwyMDYyOTg4NS42MiwyNzcyOTEuNjcwMDAwMDAwMDQsMjAzNTI1OTMuOTUsMTQ5NDk0NDUuNDU5OTk5OTk1LDMzNDg1MTg4LjQ4LDE5OCw2MC4yMywwLjUwNzU0ODY2MTI3NDQ4NDUsMC4xNTc3MDc4MTU1Njc1NTMxLDEuMCwxLjAKMjAyNC0wMS0wMSwyMDI0LTAxLEFjdHVhbCw5NTAyMDA0Ny4yOSw5NTAyMDA0Ny4yOSw0NzQ3MDAzMy4yMjAwMDAwMDYsNDQ4ODAyODYuNjIsMjU4OTc0Ni42MDAwMDAwMDksMjU4OTc0Ni42MDAwMDAwMDksMjc3MjkxLjY3MDAwMDAwMDA0LDIzMTI0NTQuOTMwMDAwMDA5LDE0MDA0NDEuMjAwMDAwMDA5LDEwNDQwMTA4MC4wMSwyMDMsNTIuNzYsMC40OTk1NzkxMzY5NzAxMzksMC4wMjcyNTQ3MzkxMTkzNzksMS4wLDEuMAoyMDI0LTAyLTAxLDIwMjQtMDIsQWN0dWFsLDk5MjA0NTczLjg1LDk5MjA0NTczLjg1LDQ5NDc0NTU3Ljg0LDQ1Mzc5MTM4LjA0LDQwOTU0MTkuNzk5OTk5OTk3LDQwOTU0MTkuNzk5OTk5OTk3LDI3NzI5MS42NzAwMDAwMDAwNCwzODE4MTI4LjEyOTk5OTk5NywyNTI5Njk2LjA5OTk5OTk5Nyw5MDczMDEyNS44LDIwNCw1Mi40OSwwLjQ5ODcxMjQ2Nzc4MjA0ODcsMC4wNDEyODI1NzAzNjAwMzU4LDEuMCwxLjAKMjAyNC0wMy0wMSwyMDI0LTAzLEFjdHVhbCwxMDk1NTI1MDEuMzYsMTA5NTUyNTAxLjM2LDU0NDIzNzE5LjA5LDQ1OTQ5OTM3LjUxLDg0NzM3ODEuNTgwMDAwMDA2LDg0NzM3ODEuNTgwMDAwMDA2LDI3NzI5MS42NzAwMDAwMDAwNCw4MTk2NDg5LjkxMDAwMDAwNiw1ODEzNDY3LjQzMDAwMDAwNSwxMjA3MTU4ODcuODEsMjAzLDUyLjIyLDAuNDk2NzgyMDc2MzA0NzUyMywwLjA3NzM0OTA0NzAzMDQ2NzYsMS4wLDEuMAoyMDI0LTA0LTAxLDIwMjQtMDQsQWN0dWFsLDExNDk0MjYzMy41LDExNDk0MjYzMy41LDU3MTQ5Nzk1LjQ5LDQ4MDU0MjI0Ljk4LDkwOTU1NzAuNTEwMDAwMDA0LDkwOTU1NzAuNTEwMDAwMDA0LDI3NzI5MS42NzAwMDAwMDAwNCw4ODE4Mjc4Ljg0MDAwMDAwNSw2Mjc5ODA5LjEzMDAwMDAwNTUsMTExNTU2MjE1LjQxLDIwNCw1MS45NSwwLjQ5NzIwMjc2NzU4NzUzNzUsMC4wNzkxMzEzOTEzMTI2OTM0LDEuMCwxLjAKMjAyNC0wNS0wMSwyMDI0LTA1LEFjdHVhbCwxMTU4MjI4MDUuOTYsMTE1ODIyODA1Ljk2LDU4MDE2MDUyLjA0MDAwMDAxLDQ4MzM5MjQ4LjY2LDk2NzY4MDMuMzgwMDAwMDEsOTY3NjgwMy4zODAwMDAwMSwyNzcyOTEuNjcwMDAwMDAwMDQsOTM5OTUxMS43MTAwMDAwMSw2NzE1NzMzLjc4MDAwMDAxMDUsMTE5NzYxODQ1LjM4LDIwNCw1MS42OCwwLjUwMDkwMzUyNzIzODI4OTcsMC4wODM1NDgzNDE3OTQ5ODI0LDEuMCwxLjAKMjAyNC0wNi0wMSwyMDI0LTA2LEFjdHVhbCwxMjAzMjE5ODkuNzMsMTIwMzIxOTg5LjczLDYwNDU4OTc3LjgwOTk5OTk5LDQ5MDgwMzM3Ljg3LDExMzc4NjM5LjkzOTk5OTk5LDExMzc4NjM5LjkzOTk5OTk5LDI3NzI5MS42NzAwMDAwMDAwNCwxMTEwMTM0OC4yNjk5OTk5OSw3OTkyMTExLjE5OTk5OTk5LDExMTUyNjQ0OS42MSwyMDcsNTEuNDEsMC41MDI0NzY1NDYwMjE3OTI1LDAuMDk0NTY4MjQ5NDU3NDIxOCwxLjAsMS4wCjIwMjQtMDctMDEsMjAyNC0wNyxBY3R1YWwsMTEzMDkzMTg0LjM2LDExMzA5MzE4NC4zNiw1Njk2ODA0NC44Myw0ODk0ODYyNi4wMyw4MDE5NDE4Ljc5OTk5OTk5Nyw4MDE5NDE4Ljc5OTk5OTk5Nyw1MzM1NDEuNjY5OTk5OTk5OSw3NDg1ODc3LjEyOTk5OTk5Nyw1MjgwNTA3Ljg0OTk5OTk5NywxMjk1MzcyNzMuMDIsMjA5LDUxLjE0LDAuNTAzNzI2NTk2MzY3Mjc5MSwwLjA3MDkwOTgzMjg1NDkzNTQsMS4wLDEuMAoyMDI0LTA4LTAxLDIwMjQtMDgsQWN0dWFsLDEwODI4MzkzMi45NiwxMDgyODM5MzIuOTYsNTQ1ODI5NDUuMjk5OTk5OTksNDk1MjM3MDUuOTcsNTA1OTIzOS4zMjk5OTk5OTEsNTA1OTIzOS4zMjk5OTk5OTEsNTMzNTQxLjY2OTk5OTk5OTksNDUyNTY5Ny42NTk5OTk5OTEsMzA2MDM3My4yMzk5OTk5OTEsMTM4MjU2NDU3LjkyLDIxMyw1MC44NywwLjUwNDA3MjQzMDc2NTU0MDIsMC4wNDY3MjE5NzYxMjA1ODM1LDEuMCwxLjAKMjAyNC0wOS0wMSwyMDI0LTA5LEFjdHVhbCwxMjU2NjY0NTMuNzMsMTI1NjY2NDUzLjczLDYyNDk0Mzk4LjkxLDUwMDU3MjExLjI0LDEyNDM3MTg3LjY3MDAwMDAwMiwxMjQzNzE4Ny42NzAwMDAwMDIsNTMzNTQxLjY2OTk5OTk5OTksMTE5MDM2NDYuMDAwMDAwMDAyLDg1OTM4MzQuNTAwMDAwMDAyLDExNDY2MjYxMy4zNSwyMTQsNTAuNiwwLjQ5NzMwMzc1MTc1NzU4NTMsMC4wOTg5Njk4MzA4NTY1NDU1LDEuMCwxLjAKMjAyNC0xMC0wMSwyMDI0LTEwLEFjdHVhbCwxMjk0NDkyODAuNjEsMTI5NDQ5MjgwLjYxLDY0NjgzNjMxLjExLDUwODgyNjg0LjI0LDEzODAwOTQ2Ljg2OTk5OTk5NSwxMzgwMDk0Ni44Njk5OTk5OTUsNTMzNTQxLjY2OTk5OTk5OTksMTMyNjc0MDUuMTk5OTk5OTk2LDk2MTY2NTMuOSwxMDI5NzkzNDAuNiwyMTQsNTcuNTMsMC40OTk2ODMyMDI2MDQwODc0LDAuMTA2NjEyNzczNzgyNjQ0NCwxLjAsMS4wCjIwMjQtMTEtMDEsMjAyNC0xMSxBY3R1YWwsMTM1MjQ5NTgwLjU5LDEzNTI0OTU4MC41OSw2NzkxNjUwMS4yMyw1MTY1MTkxMC41OCwxNjI2NDU5MC42NTAwMDAwMDYsMTYyNjQ1OTAuNjUwMDAwMDA2LDc1NDM3NS4wLDE1NTEwMjE1LjY1MDAwMDAwNiwxMTI5ODc2MS43NDAwMDAwMDYsOTg2Mzk0NDEuMzcsMjEzLDU3LjI2LDAuNTAyMTU2ODM0MzAzODY2LDAuMTIwMjU2MTI2MzMzNjE4OCwxLjAsMS4wCjIwMjQtMTItMDEsMjAyNC0xMixBY3R1YWwsMTQ4MDA0MzExLjkxLDE0ODAwNDMxMS45MSw3NTMwNjI0Ny4xNCw1MzMxMDg2Mi40MSwyMTk5NTM4NC43MzAwMDAwMDQsMjE5OTUzODQuNzMwMDAwMDA0LDc1NDM3NS4wLDIxMjQxMDA5LjczMDAwMDAwNCwxNTU5Njg1Ny4zMDAwMDAwMDQsMTAyMjI3Mjg0LjAzLDIxNSw1Ni45OSwwLjUwODgxMTE3MDIxNjM5ODksMC4xNDg2MTMxMzQ2MTg1MDQ4LDEuMCwxLjAKMjAyNS0wMS0wMSwyMDI1LTAxLEFjdHVhbCwxMDgwNzAwNDIuMjMsMTA4MDcwMDQyLjIzLDU0NTA0ODk4Ljk2MDAwMDAxLDUxNTk4OTM0Ljk0LDI5MDU5NjQuMDIwMDAwMDEwNywyOTA1OTY0LjAyMDAwMDAxMDcsNzU0Mzc1LjAsMjE1MTU4OS4wMjAwMDAwMTA3LDEyNTk3NTcuNzYwMDAwMDEwNywxNzk3NzIzNTEuNDQsMjE2LDQ5LjUyLDAuNTA0MzQ3OTAxMDAyOTQzOSwwLjAyNjg4OTYzNTI3NzYwNDQsMS4wLDEuMAoyMDI1LTAyLTAxLDIwMjUtMDIsQWN0dWFsLDExMjE4MzIwMC4zNCwxMTIxODMyMDAuMzQsNTYwMzc2NjUuNDcsNTIyODg5MDguODIsMzc0ODc1Ni42NDk5OTk5OTksMzc0ODc1Ni42NDk5OTk5OTksNzU0Mzc1LjAsMjk5NDM4MS42NDk5OTk5OTg1LDE4OTE4NTIuMjM5OTk5OTk4NCwxNjAwMzA5ODkuNTcsMjE3LDQ5LjI1LDAuNDk5NTE5MjI2NTg3OTY5MSwwLjAzMzQxNjM4MTc2MzM4NzIsMS4wLDEuMAoyMDI1LTAzLTAxLDIwMjUtMDMsQWN0dWFsLDEyNzU1MzY5OS45NywxMjc1NTM2OTkuOTcsNjMzMTI3MDUuNzIsNTI2NjgwNjUuNzgsMTA2NDQ2MzkuOTM5OTk5OTk4LDEwNjQ0NjM5LjkzOTk5OTk5OCw3NTQzNzUuMCw5ODkwMjY0LjkzOTk5OTk5OCw3MDYzNzY0LjY5OTk5OTk5NywxNTkyNDczOTMuMjgsMjE2LDQ4Ljk4LDAuNDk2MzYxMTg1NDA1NzYxMSwwLjA4MzQ1MjIyMzk4NDkwNjQsMS4wLDEuMAoyMDI1LTA0LTAxLDIwMjUtMDQsQWN0dWFsLDEyOTc2OTcxOS4xOCwxMjk3Njk3MTkuMTgsNjUwNjAyODUuMzcwMDAwMDA1LDU0NjQ5Mjg1LjA3LDEwNDExMDAwLjMwMDAwMDAwNCwxMDQxMTAwMC4zMDAwMDAwMDQsNzU0Mzc1LjAsOTY1NjYyNS4zMDAwMDAwMDQsNjg4ODUzNC45ODAwMDAwMDQsMTU2NzU3MjA0LjA1LDIxNiw0OC43MSwwLjUwMTM1MTgyMzY4NTEyODUsMC4wODAyMjY3MzA1OTQ2NzEyLDEuMCwxLjAKMjAyNS0wNS0wMSwyMDI1LTA1LEFjdHVhbCwxMzE1OTI4NzQuNzUsMTMxNTkyODc0Ljc1LDY2MTUzODQyLjM1LDU1MjIxODI0Ljg5LDEwOTMyMDE3LjQ2LDEwOTMyMDE3LjQ2LDc1NDM3NS4wLDEwMTc3NjQyLjQ2LDcyNzkyOTcuODUwMDAwMDAxNSwxNjYxNzAyOTkuODUsMjE2LDQ4LjQ0LDAuNTAyNzE1OTkwMzI3NTg0MiwwLjA4MzA3NDUzOTQxMzg0NDYsMS4wLDEuMAoyMDI1LTA2LTAxLDIwMjUtMDYsQWN0dWFsLDEzNTE4OTg0My40MiwxMzUxODk4NDMuNDIsNjc5NjMxMzMuMDI5OTk5OTksNTU5MTI5NzMuMzEsMTIwNTAxNTkuNzE5OTk5OTg0LDEyMDUwMTU5LjcxOTk5OTk4NCw5NDkxNjYuNjcsMTExMDA5OTMuMDQ5OTk5OTg0LDc5NzE4MTAuNzg5OTk5OTg0LDE2MDY5OTYzMS40NywyMTgsNDguMTcsMC41MDI3MjM2NjExMTc0NzA2LDAuMDg5MTM1MDk2MzU5MDAxMiwxLjAsMS4wCjIwMjUtMDctMDEsMjAyNS0wNyxBY3R1YWwsMTI3OTU1MzE1LjgzLDEyNzk1NTMxNS44Myw2NDM4MDg2OS4xOCw1NTQ5MTE0MC44NCw4ODg5NzI4LjMzOTk5OTk5Niw4ODg5NzI4LjMzOTk5OTk5Niw5NDkxNjYuNjcsNzk0MDU2MS42Njk5OTk5OTYsNTYwMTQ4Ny4yNDk5OTk5OTYsMTgwODE5OTgzLjk5LDIxOSw0Ny45LDAuNTAzMTUxMTg4MDcyMDU4NywwLjA2OTQ3NTI1NjEyNjIxNTEsMS4wLDEuMAoyMDI1LTA4LTAxLDIwMjUtMDgsQWN0dWFsLDEyMzUxMzA3MC4yMSwxMjM1MTMwNzAuMjEsNjI2NDE0NTQuNzUwMDAwMDEsNTYzMzY4OTguODEsNjMwNDU1NS45NDAwMDAwMDUsNjMwNDU1NS45NDAwMDAwMDUsOTQ5MTY2LjY3LDUzNTUzODkuMjcwMDAwMDA1LDM2NjI2MDcuOTUwMDAwMDA1LDE4OTc4OTY0My40MywyMjAsNDcuNjMsMC41MDcxNjQ1ODMwMTUzNDc2LDAuMDUxMDQzNjMzOTE4OTExMSwxLjAsMS4wCjIwMjUtMDktMDEsMjAyNS0wOSxBY3R1YWwsMTQwOTYwMDQzLjIsMTQwOTYwMDQzLjIsNjk5MzcyMjYuNjE5OTk5OTksNTYzODA5ODYuMTYsMTM1NTYyNDAuNDU5OTk5OTg2LDEzNTU2MjQwLjQ1OTk5OTk4NiwxMDgzMzMzLjM0LDEyNDcyOTA3LjExOTk5OTk4Niw5MDAwNzQ2LjMzOTk5OTk4NywxNjczOTMzMjkuNTYsMjE5LDQ3LjM2LDAuNDk2MTQ5Mjk4OTk1MTA2OSwwLjA5NjE3MDgwMjM5MzczODEsMS4wLDEuMAoyMDI1LTEwLTAxLDIwMjUtMTAsQWN0dWFsLDE0ODMwODcxNy45OSwxNDgzMDg3MTcuOTksNzQ0MDU1NzcuNDgsNTc3NzQ4MDIuOTIsMTY2MzA3NzQuNTYwMDAwMDAyLDE2NjMwNzc0LjU2MDAwMDAwMiwxMDgzMzMzLjM0LDE1NTQ3NDQxLjIyMDAwMDAwNCwxMTMwNjY0Ni45MTAwMDAwMDIsMTUyMTY5NTA2LjMsMjIxLDU0LjI5LDAuNTAxNjkzODg4ODU4MzUzOSwwLjExMjEzNjE4OTg3MDY1NDUsMS4wLDEuMAoyMDI1LTExLTAxLDIwMjUtMTEsQWN0dWFsLDE1NjkyMDc5Ni4yNCwxNTY5MjA3OTYuMjQsNzk0MjAzNTAuMTgsNTkzMzk0MzQuNzEsMjAwODA5MTUuNDcwMDAwMDA2LDIwMDgwOTE1LjQ3MDAwMDAwNiwxMDgzMzMzLjM0LDE4OTk3NTgyLjEzMDAwMDAwNiwxMzg5NDI1Mi42MDAwMDAwMDMsMTQ3NjA2MzM5LjAyLDIyMSw1NC4wMiwwLjUwNjExNzQzMDQ2ODExODUsMC4xMjc5Njg0NzgwNTQ5MjYzLDEuMCwxLjAKMjAyNS0xMi0wMSwyMDI1LTEyLEFjdHVhbCwxNjkwMDU5MDUuNDcsMTY5MDA1OTA1LjQ3LDg1Nzk3MDQ3LjY2LDU5NjA4ODQ1LjQ5LDI2MTg4MjAyLjE2OTk5OTk5NCwyNjE4ODIwMi4xNjk5OTk5OTQsMTA4MzMzMy4zNCwyNTEwNDg2OC44Mjk5OTk5OTQsMTg0NzQ3MTcuNjE5OTk5OTk3LDE1NTQwNzU3My40MiwyMjEsNTMuNzUsMC41MDc2NTcwOTg4NTM0NDYzLDAuMTU0OTU0MzYxNDg5MTUyOSwxLjAsMS4wCjIwMjYtMDEtMDEsMjAyNi0wMSxGb3JlY2FzdCwxMjQxNTE3MDQuMDIsMTIzMzU0NTUyLjg1LDYyNzY1NDUzLjIsNTgzNjk1ODEuOSw0Mzk1ODcxLjI5OTk5OTk5NywyMzU0NDA5Ljg2OTk5OTk5LDEwODMzMzMuMzQsMzMxMjUzNy45NTk5OTk5OTcsMjEwOTIzMy40Mjk5OTk5OTc0LDI0ODQ3OTYyMy4wOCwyMjIsNDMuMCwwLjUwNTU1NDUwNDQzMDIzMjQsMC4wMzU0MDcyNTcwNzA2ODcxLDEuODY3MDc5ODgxMDQwNDMwOCwxLjAKMjAyNi0wMi0wMSwyMDI2LTAyLEZvcmVjYXN0LDEyNzM0NjAxNy41NiwxMjgwMTA4OTUuMDIsNjQyMDIwNDguNjYsNTkyMDc4MjcuODMsNDk5NDIyMC44MzAwMDAwMDYsMjI1NjAzNy44Nzk5OTk5OTUsMTA4MzMzMy4zNCwzOTEwODg3LjQ5MDAwMDAwNiwyNTU3OTk1LjU4MDAwMDAwNiwyMjk0MTY0NzQuMzUsMjIyLDQzLjAsMC41MDQxNTQzNDk2MjI2Nzg2LDAuMDM5MjE3NzIyOTA3MTcyNSwyLjIxMzcxMzE5NzkzNjIwNSwxLjAKMjAyNi0wMy0wMSwyMDI2LTAzLEZvcmVjYXN0LDE0MDY3MTkyMC43MywxNDU1MDUwNjMuMTgsNzAyODIzODQuNzcsNTk0MDEzODAuMDksMTA4ODEwMDQuNjc5OTk5OTkyLDEwMzMyNjQ0LjY3MDAwMDAxLDEyNTMzMzMuMzQsOTYyNzY3MS4zMzk5OTk5OTIsNjg0NTU4My40NTk5OTk5OTIsMjMzMDgxMTc2LjE0LDIyMSw0My4wLDAuNDk5NjE5MTQ1MDY2NjA2MiwwLjA3NzM1MDIyNDcxODE1NSwxLjA1MzA3MDYzNDYyNTgxODcsMS4wCjIwMjYtMDQtMDEsMjAyNi0wNCxGb3JlY2FzdCwxNDY4MzY5NDUuOTksMTQ3OTk2ODAxLjQ1LDczNDc3ODI2LjU2MDAwMDAyLDYxNzYxNTY2LjgzLDExNzE2MjU5LjczMDAwMDAyLDExMzM0ODMzLjczOTk5OTk4LDEyNTMzMzMuMzQsMTA0NjI5MjYuMzkwMDAwMDIsNzQ3MjAyNC43NTAwMDAwMTksMjI1NDU3NTI1LjMxLDIyMSw0My4wLDAuNTAwNDA0MjE0MTA3MDE0LDAuMDc5NzkwOTUyMTQwODcyOCwxLjAzMzY1MDc3OTQyNDY2OTQsMS4wCjIwMjYtMDUtMDEsMjAyNi0wNSxGb3JlY2FzdCwxNDc1MDM4MTQuNjYsMTUwMTE2NjU0Ljk2LDczOTM4NDIyLjcsNjE3NzYyODMuNywxMjE2MjEzOS4wLDEyMDQ0NzUzLjMxMDAwMDAxLDEyNTMzMzMuMzQsMTA5MDg4MDUuNjYsNzgwNjQzNC4xOTk5OTk5OTksMjM2NDE4Mzc3LjU3LDIyMSw0My4wLDAuNTAxMjY0NDc4MjgwOTg1LDAuMDgyNDUzMDQ3MjUxOTIzOCwxLjAwOTc0NTc5NDQ1MzMwMjEsMS4wCjIwMjYtMDYtMDEsMjAyNi0wNixGb3JlY2FzdCwxNDk0NDc2NDcuNzcsMTU0MjE3MTM1LjEyLDc1NTc1OTkxLjU5LDYyNjg3MDM1LjUsMTI4ODg5NTYuMDkwMDAwMDA0LDEzNTc0MjE5LjcxLDEyNTMzMzMuMzQsMTE2MzU2MjIuNzUwMDAwMDA0LDgzNTE1NDcuMDIwMDAwMDAzLDIzMjgzMjc2Ni42OCwyMjIsNDMuMCwwLjUwNTcwMjExNTIwNzAwMiwwLjA4NjI0Mzk1NDIwMjg1MzEsMC45NDk1MTcyNzM1Nzg4ODc5LDEuMAoyMDI2LTA3LTAxLDIwMjYtMDcsRm9yZWNhc3QsMTQ1MjU5MzAxLjcsMTQ1OTc0ODA3Ljk5LDczOTM3NjEyLjYzOTk5OTk5LDYwOTE1MzQxLjg3LDEzMDIyMjcwLjc2OTk5OTk4OCwxMDIxMTk4My40MDAwMDAwMDYsMTI1MzMzMy4zNCwxMTc2ODkzNy40Mjk5OTk5ODksODQ4NjkyNi40Mjk5OTk5ODksMjQ5Mjg0MzM4LjYsMjIyLDQzLjAsMC41MDkwMDQzMjM4MTc0MjYxLDAuMDg5NjQ4NDQ2NzI2NjMwNCwxLjI3NTE5NTA1ODU4MTg1OTksMS4wCjIwMjYtMDgtMDEsMjAyNi0wOCxGb3JlY2FzdCwxNDE0MTQ2NTMuMjQsMTQxMDMyNjE4LjE0LDcxODI0MjkwLjIzMDAwMDAyLDYyMDAxNjU1Ljk0LDk4MjI2MzQuMjkwMDAwMDIsNjg5MDM0My4yODk5OTk5OTIsMTI1MzMzMy4zNCw4NTY5MzAwLjk1MDAwMDAyMiw2MDg3MTk5LjA3MDAwMDAyMiwyNTY3NDA4MjEuMzEsMjMxLDQzLjAsMC41MDc4OTg0OTk3OTc2NDM4LDAuMDY5NDU5ODA1MzY2MzQ4MSwxLjQyNTU2NTI5ODY0ODU3MTYsMS4wCjIwMjYtMDktMDEsMjAyNi0wOSxGb3JlY2FzdCwxNTYxNDEwMzAuMTQsMTYwNzcwNzQzLjk3LDc4NjE0MDMxLjI4OTk5OTk5LDYyODI3MzcxLjcyLDE1Nzg2NjU5LjU2OTk5OTk5MywxNjY2MzQzMy4xMjAwMDAwMDUsMTI1MzMzMy4zNCwxNDUzMzMyNi4yMjk5OTk5OTEsMTA1NjAyMTguMDI5OTk5OTk0LDIzODE1MTgxMS4zOCwyMzEsNDMuMCwwLjUwMzQ4MDkzMTQzNDMxMDgsMC4xMDExMDUxMzI2ODU3ODU4LDAuOTQ3MzgzMzc4NzAxOTc0OCwxLjAKMjAyNi0xMC0wMSwyMDI2LTEwLEZvcmVjYXN0LDE2MjE5NTY5Ny4zOTAwMDAwMiwxNjkzMjc1MDUuNDIsODE4NzQyMzkuNzgwMDAwMDIsNjIzNTQ5MjEuNjEsMTk1MTkzMTguMTcwMDAwMDE3LDE5MDUzNjA3LjA5MDAwMDAwNCwxNTIyMDgzLjM0LDE3OTk3MjM0LjgzMDAwMDAxNywxMzE1ODE0OS40ODAwMDAwMTUsMjI3MTg2NzA3Ljg2LDIyMiw0OC43LDAuNTA0Nzg2NzU1MTIwNDcxMywwLjEyMDM0NDI0MTQ1NzA2OTksMS4wMjQ0NDIxNDc3Njc2MjMsMS4wCjIwMjYtMTEtMDEsMjAyNi0xMSxGb3JlY2FzdCwxNjk2OTc1MTcuMzcsMTc5Mzk0OTU1LjgzLDg2MzEyODgyLjI0MDAwMDAxLDY0MTk5MjYxLjQyLDIyMTEzNjIwLjgyMDAwMDAwOCwyMzM3ODMyMS42NCwxNTIyMDgzLjM0LDIwNTkxNTM3LjQ4MDAwMDAwOCwxNTEwMzg3Ni40NzAwMDAwMDgsMjIzODU3MTUyLjQ4LDIzMSw0OC43LDAuNTA4NjI3ODQzMTAzOTYwNywwLjEzMDMxMTk4Nzg0MDAxNCwwLjk0NTkwMjgzOTQxMzU4MjgsMS4wCjIwMjYtMTItMDEsMjAyNi0xMixGb3JlY2FzdCwxODAxNDU5MjcuMjMsMTkzMTQ0OTkxLjI0LDkyMTA5NjQxLjYyLDY1MDMxNTQ1LjQ3LDI3MDc4MDk2LjE0OTk5OTk5LDMwNjc3MDAwLjA5MDAwMDAwNCwxNTIyMDgzLjM0LDI1NTU2MDEyLjgwOTk5OTk5LDE4ODI3MjMyLjk2OTk5OTk5LDIzMzE4MjM1OS4xNiwyMzEsNDguNywwLjUxMTMwNTcxMjE4NzQyOTUsMC4xNTAzMTIwMDg1Mjc1NTQ2LDAuODgyNjgzOTY3NDg1Njg3MywxLjAKMjAyNy0wMS0wMSwyMDI3LTAxLEZvcmVjYXN0LDE0MDI0OTk3OC4zMiwxNDAyNDk5NzguMzIsNzE1NTc2MTAuOTksNjMwNjU3MTguNTEsODQ5MTg5Mi40Nzk5OTk5OTcsODQ5MTg5Mi40Nzk5OTk5OTcsMTc2NjUyNy43OCw2NzI1MzY0LjY5OTk5OTk5Niw0NzA0MjQ2Ljg4OTk5OTk5NiwzMDY0OTg0OTcuOTgsMjMxLDQzLjAsMC41MTAyMTQ3NzM5ODU0MjgxLDAuMDYwNTQ4MjYyMzM2NDQ0MywxLjAsMS4wCjIwMjctMDItMDEsMjAyNy0wMixGb3JlY2FzdCwxNDQ3MjY3MDguNzUsMTQ0NzI2NzA4Ljc1LDczNjY5MDczLjY0LDY0NTUzOTU5LjI3LDkxMTUxMTQuMzcwMDAwMDA1LDkxMTUxMTQuMzcwMDAwMDA1LDE3NjY1MjcuNzgsNzM0ODU4Ni41OTAwMDAwMDQsNTE3MTY2My4zMDAwMDAwMDQ1LDI4ODM4NTI5MS42LDI0MCw0My4wLDAuNTA5MDIxOTY0NzUxODkzMSwwLjA2Mjk4MTU2MzMxMTQ3ODIsMS4wLDEuMAoyMDI3LTAzLTAxLDIwMjctMDMsRm9yZWNhc3QsMTU3MjY5ODA5LjQsMTU3MjY5ODA5LjQsNzk3NDE5NDguNTUwMDAwMDEsNjUzNDI2NDYuMTksMTQzOTkzMDIuMzYwMDAwMDE0LDE0Mzk5MzAyLjM2MDAwMDAxNCwxOTkyNTY5LjQ1LDEyNDA2NzMyLjkxMDAwMDAxNyw4OTY1MjczLjA0MDAwMDAxNiwyOTk1NDMzOTguMzEsMjQwLDQzLjAsMC41MDcwMzkxMzc3MzU0ODQ2LDAuMDkxNTU3OTU2NDUwMzQ5OCwxLjAsMS4wCjIwMjctMDQtMDEsMjAyNy0wNCxGb3JlY2FzdCwxNjIzNzkyMzkuMjQsMTYyMzc5MjM5LjI0LDgyMzYxMDU1LjY0MDAwMDAyLDcwMDcxMjExLjE1LDEyMjg5ODQ0LjQ5MDAwMDAxLDEyMjg5ODQ0LjQ5MDAwMDAxLDE5OTI1NjkuNDUsMTAyOTcyNzUuMDQwMDAwMDEsNzM4MzE3OS42NDAwMDAwMTEsMjk2NDAwNTg3LjY2LDI0MCw0My4wLDAuNTA3MjE0MTk4MjI4MDY2NiwwLjA3NTY4NjA1NzgyMDcwMDUsMS4wLDEuMAoyMDI3LTA1LTAxLDIwMjctMDUsRm9yZWNhc3QsMTYzNTU3NTkyLjg3LDE2MzU1NzU5Mi44Nyw4MzMyMzY5My40NSw3MDQzMDkxNy41LDEyODkyNzc1Ljk1MDAwMDAwNSwxMjg5Mjc3NS45NTAwMDAwMDUsMTk5MjU2OS40NSwxMDkwMDIwNi41MDAwMDAwMDQsNzgzNTM3OC4yMzAwMDAwMDQsMzExNDExODEyLjgxLDI0MCw0My4wLDAuNTA5NDQ1NTg0MTk5OTgyMiwwLjA3ODgyNzEzMTkyMTk0OTUsMS4wLDEuMAoyMDI3LTA2LTAxLDIwMjctMDYsRm9yZWNhc3QsMTY1ODg3NDExLjU3LDE2NTg4NzQxMS41Nyw4NDg2NTgwNC4yODk5OTk5OSw3MDgzODQ4MC4yOCwxNDAyNzMyNC4wMDk5OTk5OSwxNDAyNzMyNC4wMDk5OTk5OSwxODIyNzc3Ljc4LDEyMjA0NTQ2LjIyOTk5OTk5MSw4ODEzNjMzLjAyOTk5OTk5MiwzMTA4Mzg0NjUuMjcsMjQwLDQzLjAsMC41MTE1ODY3NjUzMDU1MDkyLDAuMDg0NTU5MzAzNjcwMTMzMSwxLjAsMS4wCg==\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Month\", type date}, {\"Month Key\", type text}, {\"Period\", type text}, {\"Revenue\", type number}, {\"Budget Revenue\", type number}, {\"Gross Profit\", type number}, {\"Operating Expense\", type number}, {\"EBITDA\", type number}, {\"Budget EBITDA\", type number}, {\"Depreciation\", type number}, {\"EBIT\", type number}, {\"Net Income\", type number}, {\"Ending Cash\", type number}, {\"Headcount\", Int64.Type}, {\"CCC Days\", type number}, {\"Gross Margin Rate\", type number}, {\"EBITDA Margin\", type number}, {\"EBITDA Attainment\", type number}, {\"Forecast Accuracy\", type number}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "KPI Revenue",
            "expression": "SUM(monthly_performance[Revenue])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Budget Revenue",
            "expression": "SUM(monthly_performance[Budget Revenue])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Gross Profit",
            "expression": "SUM(monthly_performance[Gross Profit])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Operating Expense",
            "expression": "SUM(monthly_performance[Operating Expense])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI EBITDA",
            "expression": "SUM(monthly_performance[EBITDA])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Budget EBITDA",
            "expression": "SUM(monthly_performance[Budget EBITDA])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Depreciation",
            "expression": "SUM(monthly_performance[Depreciation])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI EBIT",
            "expression": "SUM(monthly_performance[EBIT])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Net Income",
            "expression": "SUM(monthly_performance[Net Income])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Ending Cash",
            "expression": "MAX(monthly_performance[Ending Cash])",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Headcount",
            "expression": "MAX(monthly_performance[Headcount])",
            "formatString": "#,0"
          },
          {
            "name": "KPI CCC Days",
            "expression": "AVERAGE(monthly_performance[CCC Days])",
            "formatString": "0.0"
          },
          {
            "name": "KPI Gross Margin",
            "expression": "DIVIDE([KPI Gross Profit],[KPI Revenue],0)",
            "formatString": "0.0%"
          },
          {
            "name": "KPI EBITDA Margin",
            "expression": "DIVIDE([KPI EBITDA],[KPI Revenue],0)",
            "formatString": "0.0%"
          },
          {
            "name": "KPI EBITDA Attainment",
            "expression": "DIVIDE([KPI EBITDA],[KPI Budget EBITDA],0)",
            "formatString": "0.0%"
          },
          {
            "name": "KPI Forecast Accuracy",
            "expression": "AVERAGE(monthly_performance[Forecast Accuracy])",
            "formatString": "0.0%"
          },
          {
            "name": "KPI Revenue PY",
            "expression": "CALCULATE([KPI Revenue],DATEADD(dim_calendar[Date],-1,YEAR))",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI EBITDA PY",
            "expression": "CALCULATE([KPI EBITDA],DATEADD(dim_calendar[Date],-1,YEAR))",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Revenue YoY %",
            "expression": "DIVIDE([KPI Revenue]-[KPI Revenue PY],[KPI Revenue PY],0)",
            "formatString": "0.0%"
          },
          {
            "name": "KPI EBITDA YoY %",
            "expression": "DIVIDE([KPI EBITDA]-[KPI EBITDA PY],[KPI EBITDA PY],0)",
            "formatString": "0.0%"
          },
          {
            "name": "KPI Revenue Variance",
            "expression": "[KPI Revenue]-[KPI Budget Revenue]",
            "formatString": "₺#,0"
          },
          {
            "name": "KPI Revenue Variance %",
            "expression": "DIVIDE([KPI Revenue Variance],[KPI Budget Revenue],0)",
            "formatString": "0.0%"
          },
          {
            "name": "KPI EBITDA Margin Target",
            "expression": "0.10",
            "formatString": "0.0%"
          },
          {
            "name": "KPI Cash Target",
            "expression": "200000000",
            "formatString": "₺#,0"
          }
        ]
      },
      {
        "name": "department_performance",
        "columns": [
          {
            "name": "Month",
            "dataType": "dateTime",
            "sourceColumn": "Month",
            "formatString": "mmm yyyy"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "sourceColumn": "Revenue"
          },
          {
            "name": "Budget Revenue",
            "dataType": "double",
            "sourceColumn": "Budget Revenue"
          },
          {
            "name": "Operating Expense",
            "dataType": "double",
            "sourceColumn": "Operating Expense"
          },
          {
            "name": "EBITDA",
            "dataType": "double",
            "sourceColumn": "EBITDA"
          },
          {
            "name": "Budget EBITDA",
            "dataType": "double",
            "sourceColumn": "Budget EBITDA"
          },
          {
            "name": "EBITDA Margin",
            "dataType": "double",
            "sourceColumn": "EBITDA Margin"
          },
          {
            "name": "Headcount",
            "dataType": "int64",
            "sourceColumn": "Headcount",
            "formatString": "#,0"
          }
        ],
        "partitions": [
          {
            "name": "department_performance",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"TW9udGgsRGVwYXJ0bWVudCxSZXZlbnVlLEJ1ZGdldCBSZXZlbnVlLE9wZXJhdGluZyBFeHBlbnNlLEVCSVREQSxCdWRnZXQgRUJJVERBLEVCSVREQSBNYXJnaW4sSGVhZGNvdW50CjIwMjYtMDEtMDEsQ3VzdG9tZXIgU3VjY2Vzcyw3ODQ5NDEwLjYyLDc0MTI2ODkuMDMsMzM0NTY3Ni4yLDI1MzUzMzkuNTcsMjA1MTcwMy41NjAwMDAwMDAzLDAuMzIyOTk3NDQ0MzYwOTg4MSwxNgoyMDI2LTAxLTAxLEZpbmFuY2UgJiBDb3Jwb3JhdGUsMC4wLDAuMCw2ODU2NzgyLjY1LC02ODU2NzgyLjY1LC03MjM2MTkwLjExLCwyMQoyMDI2LTAxLTAxLE1hcmtldGluZywwLjAsMC4wLDc1MjE5MjkuOSwtNzUyMTkyOS45LC03NjAwNTIwLjUxLCwxOAoyMDI2LTAxLTAxLE9wZXJhdGlvbnMsMC4wLDAuMCwxMDI2ODc2My4wOCwtMTAyNjg3NjMuMDgsLTEwMzQ5ODY3LjMyLCwzMAoyMDI2LTAxLTAxLFNhbGVzLDExNjMwMjI5My40LDExNTk0MTg2My44MiwyMTMzNDIyOC44NiwzNTU1MDIwOC41NzAwMDAwMSwzNDcxOTU4MS4xMDk5OTk5ODUsMC4zMDU2NzA3NDQxNTA2MDUxLDExNQoyMDI2LTAxLTAxLFRlY2hub2xvZ3ksMC4wLDAuMCw5MDQyMjAxLjIxLC05MDQyMjAxLjIxLC05MjMwMjk2Ljg2LCwyMgoyMDI2LTAyLTAxLEN1c3RvbWVyIFN1Y2Nlc3MsODIwODYxOS43LDc1NDAwNTcuMjUsMzM5NjA5NC4zOSwyNzI4NzY1LjA3LDE5NjUyNjMuNDUsMC4zMzI0MjY3ODY2ODYxOTUyLDE2CjIwMjYtMDItMDEsRmluYW5jZSAmIENvcnBvcmF0ZSwwLjAsMC4wLDcwMTkzNzkuMjIsLTcwMTkzNzkuMjIsLTczOTY4MzMuNDYsLDIxCjIwMjYtMDItMDEsTWFya2V0aW5nLDAuMCwwLjAsNzUzNDY4Ny45NzAwMDAwMDEsLTc1MzQ2ODcuOTcwMDAwMDAxLC03ODczMTk4LjY1LCwxOAoyMDI2LTAyLTAxLE9wZXJhdGlvbnMsMC4wLDAuMCwxMDMzNzk4Ni4wLC0xMDMzNzk4Ni4wLC0xMDYzMzY2NS4yOCwsMzAKMjAyNi0wMi0wMSxTYWxlcywxMTkxMzczOTcuODYsMTIwNDcwODM3Ljc3LDIxNTYyMzI5LjIsMzY1MTQ4NjAuMCwzNTcwOTkyMS42MTk5OTk5OSwwLjMwNjQ5MzY4NDIzMjYyOTUsMTE1CjIwMjYtMDItMDEsVGVjaG5vbG9neSwwLjAsMC4wLDkzNTczNTEuMDUsLTkzNTczNTEuMDUsLTk1MTU0NDkuOCwsMjIKMjAyNi0wMy0wMSxDdXN0b21lciBTdWNjZXNzLDc4OTY1ODguMDYsODA5MDE5My4yOSwzMzczNzcxLjMzLDI1MDk4MDYuMTMsMjM5NTI2Mi44NCwwLjMxNzgzNDI0ODI3NjU5MDUsMTYKMjAyNi0wMy0wMSxGaW5hbmNlICYgQ29ycG9yYXRlLDAuMCwwLjAsNzAyNTg5MS43OSwtNzAyNTg5MS43OSwtNzUwMzU2Ni40OCwsMjEKMjAyNi0wMy0wMSxNYXJrZXRpbmcsMC4wLDAuMCw3NDgzMzIxLjIzLC03NDgzMzIxLjIzLC03NjU5NDg5LjQ1LCwxOAoyMDI2LTAzLTAxLE9wZXJhdGlvbnMsMC4wLDAuMCwxMDQ4MDUwNC45NCwtMTA0ODA1MDQuOTQsLTEwNjA5NzE3LjY3LCwzMAoyMDI2LTAzLTAxLFNhbGVzLDEzMjc3NTMzMi42NywxMzc0MTQ4NjkuODksMjE5MDgxOTMuMjgsNDI0OTA2MTQuMDMsNDMxODQxMTMuNTk5OTk5OTgsMC4zMjAwMTg4ODU4NTQzOTQ2LDExNAoyMDI2LTAzLTAxLFRlY2hub2xvZ3ksMC4wLDAuMCw5MTI5Njk3LjUyLC05MTI5Njk3LjUyLC05NDczOTU4LjE3LCwyMgoyMDI2LTA0LTAxLEN1c3RvbWVyIFN1Y2Nlc3MsODEyMTM0MC43NCw4MTYyMjQxLjQ0LDM1MzIwMjkuNzQsMjU0MTY4Ny4zMjAwMDAwMDAzLDI0NjE2NTUuMDYwMDAwMDAwNSwwLjMxMjk2NDAwNDUxMjM4OCwxNgoyMDI2LTA0LTAxLEZpbmFuY2UgJiBDb3Jwb3JhdGUsMC4wLDAuMCw3Mjg3NjU3LjQ3OTk5OTk5OSwtNzI4NzY1Ny40Nzk5OTk5OTksLTc0ODk1MTEuMDIsLDIxCjIwMjYtMDQtMDEsTWFya2V0aW5nLDAuMCwwLjAsNzczMDczOC4zOCwtNzczMDczOC4zOCwtNzg3MTc3My44OTAwMDAwMDEsLDE4CjIwMjYtMDQtMDEsT3BlcmF0aW9ucywwLjAsMC4wLDEwNjY4NzcyLjY2LC0xMDY2ODc3Mi42NiwtMTA2MTY2ODQuNzIsLDMwCjIwMjYtMDQtMDEsU2FsZXMsMTM4NzE1NjA1LjI1LDEzOTgzNDU2MC4wMSwyMzEyNzY5OS41OSw0NDI3NjQwOS45MSw0NDM0NDQ1MS42Mjk5OTk5OCwwLjMxOTE4ODM4NDI0OTk0LDExNAoyMDI2LTA0LTAxLFRlY2hub2xvZ3ksMC4wLDAuMCw5NDE0NjY4Ljk4LC05NDE0NjY4Ljk4LC05NDkzMzAzLjMyLCwyMgoyMDI2LTA1LTAxLEN1c3RvbWVyIFN1Y2Nlc3MsODQzODg2My41Miw4NDgwNDg5LjAsMzUzNTI5MC43MiwyNzU2NjE3LjA4OTk5OTk5OTQsMjYzMDQwOS4wNiwwLjMyNjY1NzM4NTAyMTkxMSwxNgoyMDI2LTA1LTAxLEZpbmFuY2UgJiBDb3Jwb3JhdGUsMC4wLDAuMCw3MTY3NjkxLjM5OTk5OTk5OSwtNzE2NzY5MS4zOTk5OTk5OTksLTc0NjA2MzguMDksLDIxCjIwMjYtMDUtMDEsTWFya2V0aW5nLDAuMCwwLjAsNzcwNTc2MS4wNSwtNzcwNTc2MS4wNSwtNzk3MTUwNS4xNCwsMTgKMjAyNi0wNS0wMSxPcGVyYXRpb25zLDAuMCwwLjAsMTA3NzM1MTYuNTMsLTEwNzczNTE2LjUzLC0xMDc4NDgyMS41LCwzMAoyMDI2LTA1LTAxLFNhbGVzLDEzOTA2NDk1MS4xNCwxNDE2MzYxNjUuOTYsMjMyMzc5MzkuMjEsNDQ0MDg1NzUuNjc5OTk5OTksNDUzNDQ0NDAuOTQwMDAwMDEsMC4zMTkzMzY5Mzc5OTg3OTc1LDExNAoyMDI2LTA1LTAxLFRlY2hub2xvZ3ksMC4wLDAuMCw5MzU2MDg0Ljc5LC05MzU2MDg0Ljc5LC05NzEzMTMxLjk2LCwyMgoyMDI2LTA2LTAxLEN1c3RvbWVyIFN1Y2Nlc3MsODI5MTU1My43LDg3MTE5OTUuNTMsMzU1Nzc5NS40NiwyNjM0NDg3LjU5MDAwMDAwMSwyNzk3NDMyLjA3OTk5OTk5ODcsMC4zMTc3MzE0NzUzNDQ2MDI5LDE2CjIwMjYtMDYtMDEsRmluYW5jZSAmIENvcnBvcmF0ZSwwLjAsMC4wLDczMzkyMjMuNjksLTczMzkyMjMuNjksLTc2NTA4OTQuNiwsMjEKMjAyNi0wNi0wMSxNYXJrZXRpbmcsMC4wLDAuMCw3ODA3NjQxLjYwOTk5OTk5OSwtNzgwNzY0MS42MDk5OTk5OTksLTgxNDQ1NDIuMzQwMDAwMDAxLCwxOAoyMDI2LTA2LTAxLE9wZXJhdGlvbnMsMC4wLDAuMCwxMDc0MzM4MS4xNSwtMTA3NDMzODEuMTUsLTEwODI4MzAzLjg0LCwzMAoyMDI2LTA2LTAxLFNhbGVzLDE0MTE1NjA5NC4wNywxNDU1MDUxMzkuNTksMjM2NjQ2MTYuNjUsNDU3MTkwOTEuODg5OTk5OTksNDcyODEyMzIuNTgwMDAwMDA2LDAuMzIzODkwMzE1ODMyMzk4MSwxMTUKMjAyNi0wNi0wMSxUZWNobm9sb2d5LDAuMCwwLjAsOTU3NDM3Ni45NCwtOTU3NDM3Ni45NCwtOTg4MDcwNC4xNywsMjIKMjAyNi0wNy0wMSxDdXN0b21lciBTdWNjZXNzLDg5OTQxNTguNSw4ODg5OTM5Ljc2LDM1MjI1MDAuNjYsMzIwNTQ5NS45MSwyOTUyMTk5LjM1OTk5OTk5OTQsMC4zNTYzOTc1MzQwMjE2NjUzLDE2CjIwMjYtMDctMDEsRmluYW5jZSAmIENvcnBvcmF0ZSwwLjAsMC4wLDcxNTQ1MTQuMTQwMDAwMDAxLC03MTU0NTE0LjE0MDAwMDAwMSwtNzUwMzYyMS4xOSwsMjEKMjAyNi0wNy0wMSxNYXJrZXRpbmcsMC4wLDAuMCw3NjMwOTM0LjcsLTc2MzA5MzQuNywtNzk1MDk5OS42MiwsMTgKMjAyNi0wNy0wMSxPcGVyYXRpb25zLDAuMCwwLjAsMTA0MTI2MjkuNywtMTA0MTI2MjkuNywtMTA4ODAxNjAuNzYsLDMwCjIwMjYtMDctMDEsU2FsZXMsMTM2MjY1MTQzLjIsMTM3MDg0ODY4LjIzLDIyOTEyODMwLjIzLDQ0Mjk2Nzg1LjgzOTk5OTk5LDQzNTAyOTg2LjkyOTk5OTk5LDAuMzI1MDc3ODk0NDYxODYxMSwxMTUKMjAyNi0wNy0wMSxUZWNobm9sb2d5LDAuMCwwLjAsOTI4MTkzMi40NCwtOTI4MTkzMi40NCwtOTkwODQyMS4zMiwsMjIKMjAyNi0wOC0wMSxDdXN0b21lciBTdWNjZXNzLDkyNzYyNTEuNTEsOTI5MzA2Ny43MywzNTQ4Nzg4LjUzMDAwMDAwMDMsMzM5MDIyNS4xLDMyMDY3MTMuMzYwMDAwMDAxLDAuMzY1NDczNjA3MTI5NDgxNSwxNgoyMDI2LTA4LTAxLEZpbmFuY2UgJiBDb3Jwb3JhdGUsMC4wLDAuMCw3MTg5NTE5LjM0LC03MTg5NTE5LjM0LC03OTAyNzEzLjIxLCwyMQoyMDI2LTA4LTAxLE1hcmtldGluZywwLjAsMC4wLDc2NzQzOTEuNDksLTc2NzQzOTEuNDksLTgyMjUyNTYuNzcsLDE4CjIwMjYtMDgtMDEsT3BlcmF0aW9ucywwLjAsMC4wLDEwNTc0MTkzLjY0LC0xMDU3NDE5My42NCwtMTEwNDU5MDkuNzcsLDMxCjIwMjYtMDgtMDEsU2FsZXMsMTMyMTM4NDAxLjczLDEzMTczOTU1MC40MSwyMzU0MDM5MS4wLDQxMzQ0ODg1LjYwMDAwMDAxLDQwODUzNDQ2LjAwOTk5OTk5LDAuMzEyODkwNzY0OTc1OTU2OSwxMjIKMjAyNi0wOC0wMSxUZWNobm9sb2d5LDAuMCwwLjAsOTQ3NDM3MS45NCwtOTQ3NDM3MS45NCwtOTk5NTkzNi4zMywsMjMKMjAyNi0wOS0wMSxDdXN0b21lciBTdWNjZXNzLDk0MDE0NDIuMTYsOTE2MTA5My4wMiwzNTY1MDk2LjUxLDM0Njc1NjQuODIsMzEwMDMxNC41MSwwLjM2ODgzMzI4NzU5NDI1MTQsMTYKMjAyNi0wOS0wMSxGaW5hbmNlICYgQ29ycG9yYXRlLDAuMCwwLjAsNzIyNDgwMy42NywtNzIyNDgwMy42NywtNzQxMDg2NC4wOCwsMjEKMjAyNi0wOS0wMSxNYXJrZXRpbmcsMC4wLDAuMCw3NzE4MTk0LjgyLC03NzE4MTk0LjgyLC04MDcyMjI4LjY1LCwxOAoyMDI2LTA5LTAxLE9wZXJhdGlvbnMsMC4wLDAuMCwxMDYzMjk5Ni4zNCwtMTA2MzI5OTYuMzQsLTEwNTU5OTQxLjEyLCwzMQoyMDI2LTA5LTAxLFNhbGVzLDE0NjczOTU4Ny45OCwxNTE2MDk2NTAuOTUsMjQxNjI2OTkuMCw0NzQxODY3MC45NTk5OTk5OSw0OTU1NDM3OC4zODk5OTk5OSwwLjMyMzE0ODQ1Mzc1MjM5MTQsMTIyCjIwMjYtMDktMDEsVGVjaG5vbG9neSwwLjAsMC4wLDk1MjM1ODEuMzgsLTk1MjM1ODEuMzgsLTk5NDgyMjUuOTMsLDIzCjIwMjYtMTAtMDEsQ3VzdG9tZXIgU3VjY2Vzcyw5Njg1NTI5LjM1LDEwMjcxMDg3LjA3LDM0NzE5NjAuOTYsMzc3MzIwOS4xNSwzODA0ODg3LjA3LDAuMzg5NTcxODA0ODY5OTExNCwxNQoyMDI2LTEwLTAxLEZpbmFuY2UgJiBDb3Jwb3JhdGUsMC4wLDAuMCw3MTI4NzE4LjI5LC03MTI4NzE4LjI5LC03NDUwNzc4LjMxLCwyMAoyMDI2LTEwLTAxLE1hcmtldGluZywwLjAsMC4wLDc2NDExNjguNTg5OTk5OTk5LC03NjQxMTY4LjU4OTk5OTk5OSwtODExMzk2OS4xNSwsMTcKMjAyNi0xMC0wMSxPcGVyYXRpb25zLDAuMCwwLjAsMTA1ODkwNDEuNTIsLTEwNTg5MDQxLjUyLC0xMTEyNDAyMy44NCwsMzAKMjAyNi0xMC0wMSxTYWxlcywxNTI1MTAxNjguMDQwMDAwMDIsMTU5MDU2NDE4LjM1LDI0MDk0NDY4LjQzLDUwNTM0NjAxLjI0MDAwMDAyLDUyMjQ0ODY3LjI0LDAuMzMxMzUyMzQxMjIwNTkyNywxMTgKMjAyNi0xMC0wMSxUZWNobm9sb2d5LDAuMCwwLjAsOTQyOTU2My44MiwtOTQyOTU2My44MiwtMTAzMDczNzUuOTIsLDIyCjIwMjYtMTEtMDEsQ3VzdG9tZXIgU3VjY2Vzcyw5NjU3NzU5LjM2LDkzMTY0OTEuMzIsMzQ3ODYwOC42MSwzNzQ1Nzg4LjQxLDMwNjg3NDAuMTkwMDAwMDAwNCwwLjM4Nzg1MjczNzkyNTMzMTcsMTUKMjAyNi0xMS0wMSxGaW5hbmNlICYgQ29ycG9yYXRlLDAuMCwwLjAsNzE2NDU2Ny42MiwtNzE2NDU2Ny42MiwtNzczMDk4NC4zLCwyMAoyMDI2LTExLTAxLE1hcmtldGluZywwLjAsMC4wLDc2ODU2NzMuMywtNzY4NTY3My4zLC04Mjc1Nzk0LjczLCwxNwoyMDI2LTExLTAxLE9wZXJhdGlvbnMsMC4wLDAuMCwxMDc1MjAxMi4xOSwtMTA3NTIwMTIuMTksLTExMjYxNjkwLjg0LCwzMQoyMDI2LTExLTAxLFNhbGVzLDE2MDAzOTc1OC4wMSwxNzAwNzg0NjQuNTEsMjU0OTUyMTkuMTMsNTM1OTMyNjYuMDg5OTk5OTksNTc5NjkwNzAuNTE5OTk5OTksMC4zMzQ4NzQ3MDA4NjQzMzkyLDEyNQoyMDI2LTExLTAxLFRlY2hub2xvZ3ksMC4wLDAuMCw5NjIzMTgwLjU3LC05NjIzMTgwLjU3LC0xMDM5MTAxOS4yLCwyMwoyMDI2LTEyLTAxLEN1c3RvbWVyIFN1Y2Nlc3MsOTcxMzc1MS44Miw5NzM2MjY2LjYzLDM0OTA2ODYuMjMsMzc3NTU5NS40NCwzMzE5MDQxLjc1MDAwMDAwMDUsMC4zODg2ODU1OTg1MTY3NjM0LDE1CjIwMjYtMTItMDEsRmluYW5jZSAmIENvcnBvcmF0ZSwwLjAsMC4wLDcyMDA3MDIuNzksLTcyMDA3MDIuNzksLTc1NTE4MDcuMjUsLDIwCjIwMjYtMTItMDEsTWFya2V0aW5nLDAuMCwwLjAsNzczMDUzMi44OSwtNzczMDUzMi44OSwtODEwNzMyNC4yODAwMDAwMDEsLDE3CjIwMjYtMTItMDEsT3BlcmF0aW9ucywwLjAsMC4wLDEwODEyMjMyLjg0LC0xMDgxMjIzMi44NCwtMTEzODUzNzMuMTQsLDMxCjIwMjYtMTItMDEsU2FsZXMsMTcwNDMyMTc1LjQxLDE4MzQwODcyNC42MSwyNjEyMzgxNC4xLDU4NzE5NTQ1Ljg1LDY0NTg5MzI3LjU2MDAwMDAyLDAuMzQ0NTMzMjE4MDMwODE3MSwxMjUKMjAyNi0xMi0wMSxUZWNobm9sb2d5LDAuMCwwLjAsOTY3MzU3Ni42MiwtOTY3MzU3Ni42MiwtMTAxODY4NjQuNTUsLDIzCg==\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Month\", type date}, {\"Department\", type text}, {\"Revenue\", type number}, {\"Budget Revenue\", type number}, {\"Operating Expense\", type number}, {\"EBITDA\", type number}, {\"Budget EBITDA\", type number}, {\"EBITDA Margin\", type number}, {\"Headcount\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Dept Revenue",
            "expression": "SUM(department_performance[Revenue])",
            "formatString": "₺#,0"
          },
          {
            "name": "Dept Budget Revenue",
            "expression": "SUM(department_performance[Budget Revenue])",
            "formatString": "₺#,0"
          },
          {
            "name": "Dept Operating Expense",
            "expression": "SUM(department_performance[Operating Expense])",
            "formatString": "₺#,0"
          },
          {
            "name": "Dept EBITDA",
            "expression": "SUM(department_performance[EBITDA])",
            "formatString": "₺#,0"
          },
          {
            "name": "Dept EBITDA Margin",
            "expression": "DIVIDE([Dept EBITDA],[Dept Revenue],0)",
            "formatString": "0.0%"
          },
          {
            "name": "Dept Headcount",
            "expression": "MAX(department_performance[Headcount])",
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "business_unit_performance",
        "columns": [
          {
            "name": "Month",
            "dataType": "dateTime",
            "sourceColumn": "Month",
            "formatString": "mmm yyyy"
          },
          {
            "name": "Business Unit",
            "dataType": "string",
            "sourceColumn": "Business Unit"
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "sourceColumn": "Revenue"
          },
          {
            "name": "Gross Profit",
            "dataType": "double",
            "sourceColumn": "Gross Profit"
          },
          {
            "name": "Operating Expense",
            "dataType": "double",
            "sourceColumn": "Operating Expense"
          },
          {
            "name": "Gross Margin",
            "dataType": "double",
            "sourceColumn": "Gross Margin"
          }
        ],
        "partitions": [
          {
            "name": "business_unit_performance",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"TW9udGgsQnVzaW5lc3MgVW5pdCxSZXZlbnVlLEdyb3NzIFByb2ZpdCxPcGVyYXRpbmcgRXhwZW5zZSxHcm9zcyBNYXJnaW4KMjAyNi0wMS0wMSxEaWdpdGFsIENvbW1lcmNlLDU0Mjc3NTE4LjY2LDI5NDA0MjQ2Ljk2LDk3ODE4NzguNDcsMC41NDE3Mzg5NjgyODYxMzc5CjIwMjYtMDEtMDEsUmV0YWlsIFN0b3JlcywzMDM3NDMyMC4zMywxNTAzODMwMi45MTAwMDAwMDIsNzYzNzc3MC41NiwwLjQ5NTA5OTIzOTk3MDM4NDYKMjAyNi0wMS0wMSxTaGFyZWQgU2VydmljZXMsMC4wLDAuMCwzMzY4OTY3Ni44NCwKMjAyNi0wMS0wMSxTdWJzY3JpcHRpb24gU2VydmljZXMsNzg0OTQxMC42Miw1ODgxMDE1Ljc3LDMzNDU2NzYuMiwwLjc0OTIzMDIzNTgzNjQ4MzYKMjAyNi0wMS0wMSxXaG9sZXNhbGUsMzE2NTA0NTQuNDEsMTI0NDE4ODcuNTU5OTk5OTk3LDM5MTQ1NzkuODMsMC4zOTMxMDI5Njc3NzUwNTI0CjIwMjYtMDItMDEsRGlnaXRhbCBDb21tZXJjZSw1NTkzNjAzNS41OCwzMDAyODc5OC4yOCw5OTA4MTAwLjQxLDAuNTM2ODQxNzMzMDM3MjQxNQoyMDI2LTAyLTAxLFJldGFpbCBTdG9yZXMsMzA1NzI2MTEuNzAwMDAwMDAzLDE0OTg2ODY3Ljg1MDAwMDAwMyw3NzQ0MjU4LjU1LDAuNDkwMjA1Njc4MTEwMjU0NQoyMDI2LTAyLTAxLFNoYXJlZCBTZXJ2aWNlcywwLjAsMC4wLDM0MjQ5NDA0LjI0LAoyMDI2LTAyLTAxLFN1YnNjcmlwdGlvbiBTZXJ2aWNlcyw4MjA4NjE5LjcsNjEyNDg1OS40NiwzMzk2MDk0LjM5LDAuNzQ2MTQ5NzQwNjE5NjA3NQoyMDI2LTAyLTAxLFdob2xlc2FsZSwzMjYyODc1MC41OCwxMzA2MTUyMy4wNywzOTA5OTcwLjI0LDAuNDAwMzA3MTc4MTExOTk3NAoyMDI2LTAzLTAxLERpZ2l0YWwgQ29tbWVyY2UsNTk4ODc2MTguNTcsMzIzMjU1NjYuNzQsOTk1ODc0NS43OCwwLjUzOTc3MDQ0ODU4MTM4ODYKMjAyNi0wMy0wMSxSZXRhaWwgU3RvcmVzLDM1NzcyMjI5LjU4LDE3NDk5MTI1LjI5LDc5MjM3MjcuMTYsMC40ODkxODE4NDU2NzkwNzQ5CjIwMjYtMDMtMDEsU2hhcmVkIFNlcnZpY2VzLDAuMCwwLjAsMzQxMTk0MTUuNDgsCjIwMjYtMDMtMDEsU3Vic2NyaXB0aW9uIFNlcnZpY2VzLDc4OTY1ODguMDYsNTg4MzU3Ny40NiwzMzczNzcxLjMzLDAuNzQ1MDc4NDMzMjc5NzAxOAoyMDI2LTAzLTAxLFdob2xlc2FsZSwzNzExNTQ4NC41MiwxNDU3NDExNS4yODAwMDAwMDUsNDAyNTcyMC4zNCwwLjM5MjY2OTQwNjU0MjM0NTMKMjAyNi0wNC0wMSxEaWdpdGFsIENvbW1lcmNlLDYzMjU1NTc2LjQ2LDM0MTI5NDg5LjY0LDEwNjMxNDYyLjYzLDAuNTM5NTQ5MTA0NjAwNzkzCjIwMjYtMDQtMDEsUmV0YWlsIFN0b3JlcywzNjcwNjIxMS4yMiwxNzk5MDY2OC43LDgyNTI2OTkuMDksMC40OTAxMjYwMDU5ODIyNjQ5CjIwMjYtMDQtMDEsU2hhcmVkIFNlcnZpY2VzLDAuMCwwLjAsMzUxMDE4MzcuNSwKMjAyNi0wNC0wMSxTdWJzY3JpcHRpb24gU2VydmljZXMsODEyMTM0MC43NCw2MDczNzE3LjA2MDAwMDAwMDUsMzUzMjAyOS43NCwwLjc0Nzg3MTIyNjQ5NDA2MjkKMjAyNi0wNC0wMSxXaG9sZXNhbGUsMzg3NTM4MTcuNTcsMTUyODM5NTEuMTYsNDI0MzUzNy44NywwLjM5NDM4NTY5MjAwMDM1NTkKMjAyNi0wNS0wMSxEaWdpdGFsIENvbW1lcmNlLDYzMzk2MjQ3LjA5LDM0MTQyNTM5LjA3MDAwMDAxLDEwNTkxMTY1LjU3LDAuNTM4NTU3NzMyMzEzODY3MwoyMDI2LTA1LTAxLFJldGFpbCBTdG9yZXMsMzg5OTg5NTQuNjQsMTkxNzkyOTguMTksODM4OTY2Ny44NiwwLjQ5MTc5MDA1ODY1NzgzOQoyMDI2LTA1LTAxLFNoYXJlZCBTZXJ2aWNlcywwLjAsMC4wLDM1MDAzMDUzLjc3LAoyMDI2LTA1LTAxLFN1YnNjcmlwdGlvbiBTZXJ2aWNlcyw4NDM4ODYzLjUyLDYyOTE5MDcuODEsMzUzNTI5MC43MiwwLjc0NTU4NzEwMzY1MzAyODQKMjAyNi0wNS0wMSxXaG9sZXNhbGUsMzY2Njk3NDkuNDEsMTQzMjQ2NzcuNjI5OTk5OTk1LDQyNTcxMDUuNzgsMC4zOTA2NDAxODMyNzAzNDQyCjIwMjYtMDYtMDEsRGlnaXRhbCBDb21tZXJjZSw2NjE0NTY4My40MSwzNTg1MjA4Ni41OCwxMDk3MzAyOS4xNywwLjU0MjAxNzAyNTYyNzcwNDUKMjAyNi0wNi0wMSxSZXRhaWwgU3RvcmVzLDQxNTk2ODQyLjYzLDIwMzgzMTI5LjUwMDAwMDAwNCw4NTE2NjE3Ljc5LDAuNDkwMDE2MjY1OTI5MjY4MwoyMDI2LTA2LTAxLFNoYXJlZCBTZXJ2aWNlcywwLjAsMC4wLDM1NDY0NjIzLjM5LAoyMDI2LTA2LTAxLFN1YnNjcmlwdGlvbiBTZXJ2aWNlcyw4MjkxNTUzLjcsNjE5MjI4My4wNTAwMDAwMDEsMzU1Nzc5NS40NiwwLjc0NjgxODE4MDc3MTExNDIKMjAyNi0wNi0wMSxXaG9sZXNhbGUsMzM0MTM1NjguMDMsMTMxNDg0OTIuNDYsNDE3NDk2OS42OSwwLjM5MzUwNzU4NDk0ODU2ODYKMjAyNi0wNy0wMSxEaWdpdGFsIENvbW1lcmNlLDYyOTkwODgxLjcxLDM0MTYwMDcyLjE3LDEwNTU0MTY2Ljg5LDAuNTQyMzAxODU3NzA4MDMzNgoyMDI2LTA3LTAxLFJldGFpbCBTdG9yZXMsNDEwMDkyMDYuMjIsMjAyMzY5ODguMTUsODMxNjMyMS4xMiwwLjQ5MzQ3NDI3MTE1MzU0NjgKMjAyNi0wNy0wMSxTaGFyZWQgU2VydmljZXMsMC4wLDAuMCwzNDQ4MDAxMC45OCwKMjAyNi0wNy0wMSxTdWJzY3JpcHRpb24gU2VydmljZXMsODk5NDE1OC41LDY3Mjc5OTYuNTcsMzUyMjUwMC42NiwwLjc0ODA0MDY5NDQxMjkzNDkKMjAyNi0wNy0wMSxXaG9sZXNhbGUsMzIyNjUwNTUuMjcsMTI4MTI1NTUuNzUsNDA0MjM0Mi4yMiwwLjM5NzEwMzE3MDY4MzY0MzUKMjAyNi0wOC0wMSxEaWdpdGFsIENvbW1lcmNlLDYxNjI3NTI1LjM1LDMzNDIwNzIxLjUsMTA4Mzk3MzAuMjUsMC41NDIzMDE4NTc5Nzk3NjM5CjIwMjYtMDgtMDEsUmV0YWlsIFN0b3JlcywzNTk0OTE4NC44NiwxNzczOTk5Ny44LDgzNDg5MDUuOTc5OTk5OTk5LDAuNDkzNDc0MjcxMjI3MTg5MQoyMDI2LTA4LTAxLFNoYXJlZCBTZXJ2aWNlcywwLjAsMC4wLDM0OTEyNDc2LjQxMDAwMDAwNCwKMjAyNi0wOC0wMSxTdWJzY3JpcHRpb24gU2VydmljZXMsOTI3NjI1MS41MSw2OTM5MDEzLjYzLDM1NDg3ODguNTMwMDAwMDAwMywwLjc0ODA0MDY5NTM3MzUxMwoyMDI2LTA4LTAxLFdob2xlc2FsZSwzNDU2MTY5MS41MiwxMzcyNDU1Ny4zMDAwMDAwMDQsNDM1MTc1NC43NzAwMDAwMDA1LDAuMzk3MTAzMTcxMDY2MDkwMwoyMDI2LTA5LTAxLERpZ2l0YWwgQ29tbWVyY2UsNjUzNzU2ODkuOTMsMzU0NTMzNTguMTEsMTEwOTY0MzkuMzcsMC41NDIzMDE4NTc4OTE4NDIyCjIwMjYtMDktMDEsUmV0YWlsIFN0b3JlcywzOTYxOTI0MS44OCwxOTU1MTA3Ni41Miw4NDk5MjY2Ljk0LDAuNDkzNDc0MjcxMzk2MTI4OQoyMDI2LTA5LTAxLFNoYXJlZCBTZXJ2aWNlcywwLjAsMC4wLDM1MDk5NTc2LjIxLAoyMDI2LTA5LTAxLFN1YnNjcmlwdGlvbiBTZXJ2aWNlcyw5NDAxNDQyLjE2LDcwMzI2NjEuMzMsMzU2NTA5Ni41MSwwLjc0ODA0MDY5NTI3OTg4MjUKMjAyNi0wOS0wMSxXaG9sZXNhbGUsNDE3NDQ2NTYuMTcsMTY1NzY5MzUuMzMwMDAwMDAyLDQ1NjY5OTIuNjksMC4zOTcxMDMxNzA4MjI0NTExCjIwMjYtMTAtMDEsRGlnaXRhbCBDb21tZXJjZSw3MDQ3MzU2OS42OCwzODIxNzk0Ny43NzAwMDAwMSwxMTE5NzQwNS4yNSwwLjU0MjMwMTg1Nzg5NTYxMzkKMjAyNi0xMC0wMSxSZXRhaWwgU3RvcmVzLDM5Nzg1MDQ1LjAyLDE5NjMyODk2LjEsODMxMTA4My4yNCwwLjQ5MzQ3NDI3MTMwMjk2MQoyMDI2LTEwLTAxLFNoYXJlZCBTZXJ2aWNlcywwLjAsMC4wLDM0Nzg4NDkyLjIyLAoyMDI2LTEwLTAxLFN1YnNjcmlwdGlvbiBTZXJ2aWNlcyw5Njg1NTI5LjM1LDcyNDUxNzAuMTA5OTk5OTk5LDM0NzE5NjAuOTYsMC43NDgwNDA2OTUzNjk5NDM4CjIwMjYtMTAtMDEsV2hvbGVzYWxlLDQyMjUxNTUzLjM0LDE2Nzc4MjI1LjgwMDAwMDAwNCw0NTg1OTc5Ljk0LDAuMzk3MTAzMTcwNzM5ODk5NwoyMDI2LTExLTAxLERpZ2l0YWwgQ29tbWVyY2UsNzkyMjQxNzkuMDcwMDAwMDEsNDI5NjM0MTkuNTEwMDAwMDA1LDEyMTU0MTM4LjMyLDAuNTQyMzAxODU4MDIyOTAwNwoyMDI2LTExLTAxLFJldGFpbCBTdG9yZXMsNDE4NDgwNTQuNTgsMjA2NTA5MzguMjQsODYwOTY2OC40MywwLjQ5MzQ3NDI3MTMxOTQwMDQKMjAyNi0xMS0wMSxTaGFyZWQgU2VydmljZXMsMC4wLDAuMCwzNTIyNTQzMy42OCwKMjAyNi0xMS0wMSxTdWJzY3JpcHRpb24gU2VydmljZXMsOTY1Nzc1OS4zNiw3MjI0Mzk3LjAyLDM0Nzg2MDguNjEsMC43NDgwNDA2OTQ2MDY4Mjg1CjIwMjYtMTEtMDEsV2hvbGVzYWxlLDM4OTY3NTI0LjM2LDE1NDc0MTI3LjQ3LDQ3MzE0MTIuMzgsMC4zOTcxMDMxNzA1MDI3NzE5CjIwMjYtMTItMDEsRGlnaXRhbCBDb21tZXJjZSw4NTc1MDk2Ny42MSw0NjUwMjkwOS4wNSwxMjU5NTM4MC4wNCwwLjU0MjMwMTg1Nzg4MTA0MTMKMjAyNi0xMi0wMSxSZXRhaWwgU3RvcmVzLDQ4OTA3NTUzLjcxLDI0MTM0NjE5LjQzMDAwMDAwMyw4ODg2Nzc1LjI1LDAuNDkzNDc0MjcxMzM4Njg4MQoyMDI2LTEyLTAxLFNoYXJlZCBTZXJ2aWNlcywwLjAsMC4wLDM1NDE3MDQ1LjE0LAoyMDI2LTEyLTAxLFN1YnNjcmlwdGlvbiBTZXJ2aWNlcyw5NzEzNzUxLjgyLDcyNjYyODEuNjcsMzQ5MDY4Ni4yMywwLjc0ODA0MDY5NTc3MzA5ODMKMjAyNi0xMi0wMSxXaG9sZXNhbGUsMzU3NzM2NTQuMDksMTQyMDU4MzEuNDY5OTk5OTk1LDQ2NDE2NTguODEwMDAwMDAwNSwwLjM5NzEwMzE3MDc5MzI1MjIK\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Month\", type date}, {\"Business Unit\", type text}, {\"Revenue\", type number}, {\"Gross Profit\", type number}, {\"Operating Expense\", type number}, {\"Gross Margin\", type number}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "BU Revenue",
            "expression": "SUM(business_unit_performance[Revenue])",
            "formatString": "₺#,0"
          },
          {
            "name": "BU Gross Profit",
            "expression": "SUM(business_unit_performance[Gross Profit])",
            "formatString": "₺#,0"
          },
          {
            "name": "BU Operating Expense",
            "expression": "SUM(business_unit_performance[Operating Expense])",
            "formatString": "₺#,0"
          },
          {
            "name": "BU Gross Margin",
            "expression": "DIVIDE([BU Gross Profit],[BU Revenue],0)",
            "formatString": "0.0%"
          }
        ]
      },
      {
        "name": "P&L Stages",
        "columns": [
          {
            "name": "Stage",
            "dataType": "string",
            "sourceColumn": "Stage"
          },
          {
            "name": "Stage Order",
            "dataType": "int64",
            "sourceColumn": "Stage Order",
            "formatString": "#,0"
          }
        ],
        "partitions": [
          {
            "name": "P&L Stages",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"U3RhZ2UsU3RhZ2UgT3JkZXIKUmV2ZW51ZSwxCkdyb3NzIFByb2ZpdCwyCkVCSVREQSwzCkVCSVQsNApOZXQgSW5jb21lLDUK\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Stage\", type text}, {\"Stage Order\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "P&L Stage Value",
            "expression": "SWITCH(SELECTEDVALUE('P&L Stages'[Stage]),\"Revenue\",[KPI Revenue],\"Gross Profit\",[KPI Gross Profit],\"EBITDA\",[KPI EBITDA],\"EBIT\",[KPI EBIT],\"Net Income\",[KPI Net Income],BLANK())",
            "formatString": "₺#,0"
          }
        ]
      },
      {
        "name": "scenario_summary",
        "columns": [
          {
            "name": "Scenario",
            "dataType": "string",
            "sourceColumn": "Scenario"
          },
          {
            "name": "Scenario Order",
            "dataType": "int64",
            "sourceColumn": "Scenario Order",
            "formatString": "#,0"
          },
          {
            "name": "Revenue",
            "dataType": "double",
            "sourceColumn": "Revenue"
          },
          {
            "name": "EBITDA",
            "dataType": "double",
            "sourceColumn": "EBITDA"
          },
          {
            "name": "Ending Cash",
            "dataType": "double",
            "sourceColumn": "Ending Cash"
          },
          {
            "name": "Minimum Cash",
            "dataType": "double",
            "sourceColumn": "Minimum Cash"
          },
          {
            "name": "EBITDA Margin",
            "dataType": "double",
            "sourceColumn": "EBITDA Margin"
          },
          {
            "name": "CCC Days",
            "dataType": "double",
            "sourceColumn": "CCC Days"
          }
        ],
        "partitions": [
          {
            "name": "scenario_summary",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"U2NlbmFyaW8sU2NlbmFyaW8gT3JkZXIsUmV2ZW51ZSxFQklUREEsRW5kaW5nIENhc2gsTWluaW11bSBDYXNoLEVCSVREQSBNYXJnaW4sQ0NDIERheXMKVXBzaWRlLDEsMTg3Njc0OTA0OS4yNCwyMDYyNTU4MDguMTIsMjkzMjg2OTc5LjQ3LDI3NDIwMTcyMy4zNiwwLjEwOTkwMSwzNi44NQpCYXNlLDIsMTc5MDgxMjE3Ny44LDE2NDM4MTA1MS40LDI0NTYyOTAyNS44MSwyMzYzMDM4MTkuMTIsMC4wOTE3OTEsNDUuODUKRG93bnNpZGUsMywxNjk1MzI2NzY1LjA5LDExODU0MTI1Mi44OSwxODU2MDA4MDcuNzIsMTgzMzk2NzYyLjQ2LDAuMDY5OTIyLDU5Ljg1ClN0cmVzcyw0LDE1OTk4NDEzNTIuMzksNzEyOTY4MzQuODcsMTE1ODc3NjgzLjkyLDExNTg3NzY4My45MiwwLjA0NDU2NSw3Ny44NQo=\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Scenario\", type text}, {\"Scenario Order\", Int64.Type}, {\"Revenue\", type number}, {\"EBITDA\", type number}, {\"Ending Cash\", type number}, {\"Minimum Cash\", type number}, {\"EBITDA Margin\", type number}, {\"CCC Days\", type number}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Scenario Revenue",
            "expression": "SUM(scenario_summary[Revenue])",
            "formatString": "₺#,0"
          },
          {
            "name": "Scenario EBITDA",
            "expression": "SUM(scenario_summary[EBITDA])",
            "formatString": "₺#,0"
          },
          {
            "name": "Scenario Ending Cash",
            "expression": "SUM(scenario_summary[Ending Cash])",
            "formatString": "₺#,0"
          },
          {
            "name": "Scenario Minimum Cash",
            "expression": "SUM(scenario_summary[Minimum Cash])",
            "formatString": "₺#,0"
          },
          {
            "name": "Scenario EBITDA Margin",
            "expression": "DIVIDE([Scenario EBITDA],[Scenario Revenue],0)",
            "formatString": "0.0%"
          }
        ]
      },
      {
        "name": "variance_analysis",
        "columns": [
          {
            "name": "Metric",
            "dataType": "string",
            "sourceColumn": "Metric"
          },
          {
            "name": "Metric Order",
            "dataType": "int64",
            "sourceColumn": "Metric Order",
            "formatString": "#,0"
          },
          {
            "name": "Forecast Value",
            "dataType": "double",
            "sourceColumn": "Forecast Value"
          },
          {
            "name": "Budget Value",
            "dataType": "double",
            "sourceColumn": "Budget Value"
          },
          {
            "name": "Variance",
            "dataType": "double",
            "sourceColumn": "Variance"
          },
          {
            "name": "Variance Rate",
            "dataType": "double",
            "sourceColumn": "Variance Rate"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          }
        ],
        "partitions": [
          {
            "name": "variance_analysis",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"TWV0cmljLE1ldHJpYyBPcmRlcixGb3JlY2FzdCBWYWx1ZSxCdWRnZXQgVmFsdWUsVmFyaWFuY2UsVmFyaWFuY2UgUmF0ZSxTdGF0dXMKUmV2ZW51ZSwxLDE3OTA4MTIxNzcuOCwxODM4ODQ2NzI1LjE3LC00ODAzNDU0Ny4zNywtMC4wMjYxMjIsVW5mYXZvcmFibGUKQ09HUywyLDg4NTg5NzM1Mi41Miw4OTY2NzE0MTMuOTcsLTEwNzc0MDYxLjQ1LC0wLjAxMjAxNixGYXZvcmFibGUKR3Jvc3MgUHJvZml0LDMsOTA0OTE0ODI1LjI4LDk0MjE3NTMxMS4yLC0zNzI2MDQ4NS45MiwtMC4wMzk1NDcsVW5mYXZvcmFibGUKT3BlcmF0aW5nIEV4cGVuc2UsNCw3NDA1MzM3NzMuODgsNzgzNDAzNzIzLjM5LC00Mjg2OTk0OS41MSwtMC4wNTQ3MjMsRmF2b3JhYmxlCkVCSVREQSw1LDE2NDM4MTA1MS40LDE1ODc3MTU4Ny44MSw1NjA5NDYzLjU5LDAuMDM1MzMsRmF2b3JhYmxlCkRlcHJlY2lhdGlvbiw2LDE1NTA2MjUwLjA4LDE1Njc3MDgzLjM2LC0xNzA4MzMuMjgsLTAuMDEwODk3LEZhdm9yYWJsZQpFQklULDcsMTQ4ODc0ODAxLjMyLDE0MzA5NDUwNC40NSw1NzgwMjk2Ljg3LDAuMDQwMzk1LEZhdm9yYWJsZQpJbnRlcmVzdCw4LDU3MTk1NzMuNDQsNTQzNjQyNi4yNCwyODMxNDcuMiwwLjA1MjA4MyxVbmZhdm9yYWJsZQpUYXgsOSwzNTc4ODgwNi45OSwzNDQxNDUxOS41NSwxMzc0Mjg3LjQ0LDAuMDM5OTMzLFVuZmF2b3JhYmxlCk5ldCBJbmNvbWUsMTAsMTA3MzY2NDIwLjg5LDEwMzI0MzU1OC42Niw0MTIyODYyLjIzLDAuMDM5OTMzLEZhdm9yYWJsZQo=\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Metric\", type text}, {\"Metric Order\", Int64.Type}, {\"Forecast Value\", type number}, {\"Budget Value\", type number}, {\"Variance\", type number}, {\"Variance Rate\", type number}, {\"Status\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "risk_summary",
        "columns": [
          {
            "name": "Risk Metric",
            "dataType": "string",
            "sourceColumn": "Risk Metric"
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value"
          },
          {
            "name": "Unit",
            "dataType": "string",
            "sourceColumn": "Unit"
          }
        ],
        "partitions": [
          {
            "name": "risk_summary",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"UmlzayBNZXRyaWMsVmFsdWUsVW5pdApSZXZlbnVlIFAxMCwxNjE5MzI0NzY1LjQ2MyxUUlkKUmV2ZW51ZSBQNTAsMTc4ODc5MTY0NS45MDUsVFJZClJldmVudWUgUDkwLDE5NTg3NDAzNzYuNzY1LFRSWQpFQklUREEgUDEwLDYwMzI0NTgwLjk2NCxUUlkKRUJJVERBIFA1MCwxNjM2NjIwNDEuMTksVFJZCkVCSVREQSBQOTAsMjY4NTMxMTg4Ljc4MDAwMDEsVFJZClByb2JhYmlsaXR5IEVCSVREQSBCZWxvdyBCdWRnZXQsMC40NzYyLFBlcmNlbnQKUHJvYmFiaWxpdHkgTmVnYXRpdmUgQ2FzaCwwLjAsUGVyY2VudApFbmRpbmcgQ2FzaCBQMTAsMTcwMDQxNTI3LjkwNyxUUlkK\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Risk Metric\", type text}, {\"Value\", type number}, {\"Unit\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "capex_summary",
        "columns": [
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Capex Spend",
            "dataType": "double",
            "sourceColumn": "Capex Spend"
          },
          {
            "name": "Depreciation",
            "dataType": "double",
            "sourceColumn": "Depreciation"
          },
          {
            "name": "Remaining NBV",
            "dataType": "double",
            "sourceColumn": "Remaining NBV"
          }
        ],
        "partitions": [
          {
            "name": "capex_summary",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Binary = Binary.FromText(\"RGVwYXJ0bWVudCxDYXBleCBTcGVuZCxEZXByZWNpYXRpb24sUmVtYWluaW5nIE5CVgpDdXN0b21lciBTdWNjZXNzLDcyMzMzMzMuMzYsMjMzNzUwMC4wNCwyMTA4NDM3NTAuMApGaW5hbmNlICYgQ29ycG9yYXRlLDMzOTk5OTkuOTksMTcwMDAwMC4wLDExMzA1MDAwMC4wCk9wZXJhdGlvbnMsMTU4NDAwMDAuMCwyNjQ5OTk5Ljk2LDM0NzY3NTAwMC4wClNhbGVzLDAuMCwyOTAwMDAwLjA0LDExMzg4MDAwMC4wClRlY2hub2xvZ3ksMTI4OTk5OTkuOTcsNTkxODc1MC4wNCwyNDY4NDM3NTAuMAo=\", BinaryEncoding.Base64),",
                "    Source = Csv.Document(Binary, [Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Promoted, {{\"Department\", type text}, {\"Capex Spend\", type number}, {\"Depreciation\", type number}, {\"Remaining NBV\", type number}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_monthly_calendar",
        "fromTable": "monthly_performance",
        "fromColumn": "Month",
        "toTable": "dim_calendar",
        "toColumn": "Date"
      },
      {
        "name": "rel_department_calendar",
        "fromTable": "department_performance",
        "fromColumn": "Month",
        "toTable": "dim_calendar",
        "toColumn": "Date"
      },
      {
        "name": "rel_business_unit_calendar",
        "fromTable": "business_unit_performance",
        "fromColumn": "Month",
        "toTable": "dim_calendar",
        "toColumn": "Date"
      }
    ]
  }
}